### ISSUE TITLE
Click on user in 'who to follow', but can't see follow button

### ISSUE THREAD

**Issue by jimmytidey** [Gargron/mastodon#102]
Clicking on a user in 'who to follow' results in their profile appearing in the 4th column. 

However the drop down, which I assume will include a follow option, appears off the screen.

Chrome, mac, screen resolution 1280 x 800. 

![screen shot 2016-10-21 at 11 16 14](https://cloud.githubusercontent.com/assets/466068/19595134/4ab4bae6-9780-11e6-8332-7cd54c9d7458.png)

**Comment by Gargron** [comment]
Okay, just tried in Chrome, the dropdown button doesn't even work for me there. Will investigate.

**Comment by Gargron** [comment]
This was fixed when I moved the dropdown icon to the left side instead or right. There's also #108
