### ISSUE TITLE
Frozen screen while signing up

### ISSUE THREAD

**Issue by beccanalia** [Gargron/mastodon#113]
Hello.

I hope the screen-freeze is due to the volume of people Aral is sending to Mastodon. 

My experience: 
I typed in a UN, then an email address, then the same password, twice. I was told that "something is wrong below" with the line under the Confirm Password became a bright red (nice touch, by the way.

I clicked on the form to re-enter the PW I'd chosen, but the screen froze. I'm going to check things on my end, but please also check things on your end.

I look forward to trying out this new social space.

**Comment by Gargron** [comment]
What exactly do you mean by the screen froze? Blank screen? Form still there but you can't click submit? I need more details

**Comment by beccanalia** [comment]
Hello. Thanks for asking.

The form remained on the page but I couldn't enter anything into it. It was
frozen.

B

**Comment by PalleZingmark** [comment]
I had the same issue, I think. I signed up and hit "Sign up" and nothing happened, so I did a reload and then I got a message saying I should check my email for a confirmation.

**Comment by Gargron** [comment]
I haven't had any similar reports for a while and I can't really tell what went wrong so I'm gonna close this, sorry.

**Comment by beccanalia** [comment]
Hello.

That's ok. I got it to work, or, something happened and I was able to sign
in.


Thanks!
Happy Holidays!
