### ISSUE TITLE
Use an anchor for hashtags

### ISSUE THREAD

**Issue by MichielBijl** [Gargron/mastodon#118]
Keyboard users use the <kbd>tab</kbd> key to navigate between the focusable elements on a page to interact with them. For links, they use the <kbd>enter</kbd> / <kbd>return</kbd> key to activate the item. Currently, hashtags are marked up with a `p` element; these aren’t focusable let alone that a keyboard user can activate them.

**Comment by MichielBijl** [comment]
Or am I crazy and are hashtags not supported at all? I’m still figuring out the UI.

**Comment by Gargron** [comment]
Hashtags are not a thing yet 😆

**Comment by MichielBijl** [comment]
That explains why they’re in `p`’s 😬

**Comment by Gargron** [comment]
:white_check_mark:
