### ISSUE TITLE
No confirmation mail if first delivery attempt failed

### ISSUE THREAD

**Issue by rollbear** [Gargron/mastodon#120]
The one making an initial mistake was I. I registered using a mail alias before having updated said alias for my mail server.

However, after that all attempts seem to go to /dev/null. Having correctly updated my mail server for the alias, I can go to "didn't receive confirmation instructions" and fill in details. It says I'll receive instructions shortly. I don't. Nothing happens. Not even a failed attempt to deliver mail to my domain.

**Comment by Gargron** [comment]
Mailgun (the e-mail delivery service I am using) marks hard bounces (like mailbox doesn't exist) for the future and doesn't try sending anything to them after. I guessed which e-mail was yours and removed it from the bounce list. Try again now.

**Comment by rollbear** [comment]
Worked. Thanks.
