### ISSUE TITLE
Pressing "Enter" does not auto-complete mentioned user name with chosen suggestion

### ISSUE THREAD

**Issue by svetlik** [Gargron/mastodon#124]
1. Start mentioning someone
2. Navigate to the correct suggestion from the auto-suggest.
3. Press "Enter"

The selected name is not automatically written in the mip. 
Note: This works if the suggestion has been clicked.
![screen shot 2016-11-02 at 3 30 27 am](https://cloud.githubusercontent.com/assets/1100307/19913611/df50f2b6-a0ac-11e6-8671-7a958eaa4bb8.png)

**Comment by Gargron** [comment]
Depends on https://github.com/moroshko/react-autosuggest/issues/281

**Comment by LogicalDash** [comment]
Up and down arrows still not working for me. Chromium 53.0.2785.143

**Comment by LogicalDash** [comment]
Never mind, I forgot to refresh
