### ISSUE TITLE
Image gallery not scrolling

### ISSUE THREAD

**Issue by fermuch** [Gargron/mastodon#128]
If an image bigger than the screen is showed, there is no way to scroll.

Example:
![image](https://cloud.githubusercontent.com/assets/998598/19928895/ca2f24c6-a0e7-11e6-9223-1a73d0c5a639.png)

This seems to be a problem with how the javascript modal is handling the scroll. If I try to open an image, I get this error in the console:
![image](https://cloud.githubusercontent.com/assets/998598/19928938/06813f0e-a0e8-11e6-8e0d-bde193996a35.png)

Browser: Opera Developer 42.0.2372.0.

**Comment by Gargron** [comment]
This is now fixed
