### ISSUE TITLE
Can't follow a mastodon account from GNU social

### ISSUE THREAD

**Issue by picsi** [Gargron/mastodon#137]
This is more a question than a bug report. Is it possible to do so?

**Comment by Gargron** [comment]
Yes. Mind that the Qvitter theme hides this functionality, but if you switch to GNU social "classic", you'll find a "follow remote user" page, where you can enter somebody@mastodon.social (or other Mastodon server, you know what I mean) to follow them.

**Comment by picsi** [comment]
Is it possible to implement a 'remote follow' button on mastodon?
