### ISSUE TITLE
PgUp/PgDown/Arrows don't work for navigation in timelines?

### ISSUE THREAD

**Issue by jean** [Gargron/mastodon#140]
I can't click in a timeline to give it focus: there's no neutral clickable space, everything navigates somewhere (a common antipattern). This means that scrolling requires using the mouse/touchpad/scrollbar. I prefer using the keyboard. 
I can TabTabTab until a timeline has focus, but this is cumbersome and there's no visual feedback. 
(Firefox 49.0.2 on Mint Linux)

**Comment by Gargron** [comment]
If I remove the click handler from status items, how do you suggest opening a status should work?

**Comment by jean** [comment]
There is ample space for neutral areas .. currently the area under the avatar or to the right of the `...` icon. Clicking the timeline headers could also focus that timeline. It would be nice if only clicking the actual text opened a status, and not also whitespace after line endings or between paragraphs.

**Comment by fjordaan** [comment]
I agree with jean that there needs to be some neutral area in each column you can click to give that column keyboard focus. 

An easy solution (@jean: you could even do this as a user stylesheet) is to change the 10px left margin on `.column` to 10px left padding. When clicked, the padding will give focus to that column.

To make this more discoverable for users, I suggest a subtle background colour change on `.column:hover`, and also a background colour change on the status `div` on hover.

**Comment by fjordaan** [comment]
@jean: see if this user stylesheet does it for you (use the Stylish extension to apply):
```
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain("mastodon.social") {
  .column, .drawer {
    margin-left: 0;
    padding-left: 10px;
  }
  .column:hover, .drawer:hover {
    background: #454b5e !important;
  }
  .column > div > div {
    background-color: #282c37;
  }
  .scrollable > div > div:hover {
    background-color: #454b5e;
  }
}
```
@Gargron you'd make it a little easier to hack if you used class names :)

**Comment by Gargron** [comment]
@fjordaan It would probably be a good idea to move styles out of JS and into CSS at some point

**Comment by fjordaan** [comment]
@Gargron Apparently doing one's CSS in JS is all the rage nowadays. I don't get it.

**Comment by Gargron** [comment]
@fjordaan Quicker prototyping, as it were, plus you can sort of re-use components without always having to carry the CSS around too.

**Comment by jean** [comment]
:heart:
