### ISSUE TITLE
How to detect if a server is using mastodon?

### ISSUE THREAD

**Issue by annando** [Gargron/mastodon#141]
In Friendica we are having some code that does a server detection. When a server url is entered the system detects which protocol is used the best for the server and which software in which version it using.

How can we get this information (software and version) from mastodon?

**Comment by Gargron** [comment]
Having a public resource that reveals which version of the software is running on the server will be way too useful for bots to scan for potential vulnarabilities - is there any alternative way in which Friendica can figure out that the OStatus protocol is supported on a server?

For example, Mastodon checks if a Webfinger endpoint is available, and if so, whether an Atom feed, a Salmon endpoint and a PubSubHubbub hub are linked.

**Comment by annando** [comment]
Is there a way to check if the server is using mastodon? Friendica does have some internal statistics so that people can see which servers are out there in the world and which software they are using.

**Comment by Gargron** [comment]
How about I add a `Server` header to all responses? Would that be sufficient?

**Comment by annando** [comment]
It would be the best to have something that doesn't cost too much on the server (Mastodon) side. Such a header is used for Diaspora as well. They are having a header like ````X-Diaspora-Version: 0.6.0.1```` at every request.

Friendica and GNU Social are working with an API call: https://pirati.ca/api/statusnet/version

You could do the same, but you could simply return "Mastodon" there.
