### ISSUE TITLE
Unreblogging a status removes it from home feed

### ISSUE THREAD

**Issue by Gargron** [Gargron/mastodon#147]
... even if someone else you follow reblogged it before or even if you follow the original author.

This is because the home feed deduplicates statuses: it's a redis sorted set with status_id as key and (reblog_of_id|status_id) as value, which ensures that a status gets "bumped up" by subsequent reblogs, rather than appearing more than once on the feed. That's good, except in the case that someone reblogs and then undoes the reblog. Since no other references to it in the feed remain, when the reblog gets removed, it's removed for good.

Deleting a status is a process that is just as computationally expensive as distributing it in the first place (aka you need to iterate over all followers to insert/remove it). Perhaps during removal we could check if the follower follows the original status author, in which case instead of removing the status, the key would be set to the original status_id. Then the status would go back to its old place in the feed.

However, this does not solve the issue when the status has previously been reblogged by someone else on the feed. That previous reblog-status_id is not kept anywhere close to the process. The naive approach to this problem would be to rebuild the entire home feed from scratch - then the information would definitely be available. However, it's not a viable approach, as you would need to rebuild all home feeds for all followers, just for a simple unreblog action.

Without thinking about implementation details, for each follower, we need to get the ID of the most recent reblog of that status by a person that follower is following.

**Comment by ineffyble** [comment]
Note that this can happen with your **own** tweets too, if you reboost then unboost.
