### ISSUE TITLE
user_mailer.rb: ArgumentError: wrong number of arguments (given 3, expected 2)

### ISSUE THREAD

**Issue by tchncs** [Gargron/mastodon#148]
Hi there,

today i tried to set up a mastodon instance but getting stuck with the following error:

````
method=POST path=/auth format=html controller=Auth::RegistrationsController action=create status=500 error='ArgumentError: wrong number of arguments (given 3, expected 2)' duration=689.89 view=0.00 db=0.00

app/mailers/user_mailer.rb:7:in `confirmation_instructions'
````

I am on the master branch and hope this error is not just my fault. :3

**Comment by Gargron** [comment]
Not your fault, it's my bad. I tested if the custom devise mailer works but not if this particular method works and voilà, we have a problem
