### ISSUE TITLE
Cull feeds of inactive users to save resources

### ISSUE THREAD

**Issue by Gargron** [Gargron/mastodon#155]
If somebody hasn't logged in for x days, it makes sense to remove their home/mentions feeds from redis and not do the redis and actioncable distribution to them during Fan Out On Write. It will save time during distribution and RAM for storage. If such a user would come back, the feeds would be re-generated from scratch again.

**Comment by Gargron** [comment]
:white_check_mark:

**Comment by silasary** [comment]
What do we define as Inactive?

**Comment by Gargron** [comment]
Last login longer than 14 days ago.

**Comment by silasary** [comment]
I periodically go on camping trips where I don't have reliable cellular
reception, which can often go for 14-30 days. (In fact, I'm on one now)

I'd hate to get back and find that I lost all my toots while I was away.

The inactivity threshold should be raised to 2-3 months, so as to afford
people who occasionally go offline for a fortnight.

**Comment by Gargron** [comment]
If everything works correctly you should not lose any toots. They'd still be served to you when you log back in.
