### ISSUE TITLE
How to post to an account using PHP?

### ISSUE THREAD

**Issue by LiamDawe** [Gargron/mastodon#158]
Is there a way to auto-post to a Mastodon account using PHP?

**Comment by Gargron** [comment]
Hey! Yes. See:

- [Testing the API with cURL](https://github.com/Gargron/mastodon/wiki/Testing-with-cURL)
- [API documentation](https://github.com/Gargron/mastodon/wiki/API)

I wrote a Ruby library for the API: <https://github.com/Gargron/mastodon-api> A PHP one wouldn't be too different. Does this answer your question?

**Comment by LiamDawe** [comment]
Was looking more for a basic example of posting a status message with PHP :)

**Comment by Gargron** [comment]
Someone's Python example: <https://gist.github.com/anonymous/db81fbea08902881db14260447207f3e>

**Comment by LiamDawe** [comment]
That's a completely different language :/

**Comment by qwertygc** [comment]
https://github.com/Lusitanian/PHPoAuthLib/
