### ISSUE TITLE
Expand post context menu

### ISSUE THREAD

**Issue by unsmell** [Gargron/mastodon#159]
![ss 2016-11-21 at 06 54 04](https://cloud.githubusercontent.com/assets/2267475/20498241/e7bf7584-b01b-11e6-9168-39b6becee61a.png)
Add further user interaction to this context menu, such as blocking, muting (?), etc

**Comment by hoodiek** [comment]
i would believe this can be clsoed, as blocking and expanding already exist in this menu. the only thing that was also requested was "mute" which does not exist yet. i would advise we can work such things on a case by case basis as such features are added

**Comment by swaldie** [comment]
Yeah I'm gonna call this added.  I think specific requests to improve this context menu can go in the relevant enhancement requests from here forward.
