### ISSUE TITLE
Allow being logged into more than one account

### ISSUE THREAD

**Issue by LiamDawe** [Gargron/mastodon#161]
For those of us with more than one account, please follow how Tweetdeck does it and allow us to choose who to post as and let us login to more accounts.

**Comment by Gargron** [comment]
This is something that a 3rd party app or mobile app could implement. It'd be really complicated on the main site. Of all the sites I know only Google allows you to be signed on from multiple accounts, and even then it's a switch.

**Comment by LiamDawe** [comment]
From doing software development myself, I know multiple ways this could be achieved.

You must be doing something to store the logged in session, can you not split that into multiples?

**Comment by ticki** [comment]
@Gargron Tweetdeck allows you to do something like this. It's not signing in, but it allows you to control multiple users at once.
