### ISSUE TITLE
Sometimes getting duplicate notifications

### ISSUE THREAD

**Issue by Ragzouken** [Gargron/mastodon#165]
![doublefav](https://cloud.githubusercontent.com/assets/527158/20503480/9399bcf2-b03a-11e6-8083-cd850d8cb164.PNG)

**Comment by Gargron** [comment]
I'm pretty sure someone fav'd, unfav'd and fav'd again.

**Comment by swaldie** [comment]
I'm going to go ahead and close this for now.  If someone can show a consistent reproduction of this, then we can revisit it.
