### ISSUE TITLE
Show favorites/reblogs in post view

### ISSUE THREAD

**Issue by duckinator** [Gargron/mastodon#166]
It'd be nice to see the number of favorites and reblogs when viewing an individual post.

E.g., some of the replies to https://mastodon.social/users/duckinator/updates/79300 have been favorited, but there's no way to tell that other than scrolling through the notifications section of the homepage.

(Also, what's the terminology you use for those? posts? updates? something else?)

**Comment by swaldie** [comment]
At this time I'm going to close this and add it to #174, as I see these issues as being directly related.
