### ISSUE TITLE
Admin dashboard

### ISSUE THREAD

**Issue by Gargron** [Gargron/mastodon#17]
Mastodon should provide an Admin dashboard with an overview of what is happening behind the scenes:
- How many local users do we have?
- How many remote users are we subscribed to?
- What other instances are we aware of?
- How many local statuses are we hosting?

Furthermore, the admin dashboard should be the place where account or status suspensions from #9 should be managed.

**Comment by swaldie** [comment]
#287 Has a number of suggestions that would be relevant to Admin functionality of the site.

**Comment by hoodiek** [comment]
didn't this already get added? not to like, pressure for it to be closed, i don't know any details of the admin stuff but i remember functionality occuring

**Comment by swaldie** [comment]
@Gargron Is this in a state where it's cool to close?

**Comment by Gargron** [comment]
I suppose it's not a pressing issue anymore. It'd be nice to have a dashboard with stats but main admin functionality is already implemented, so imma close this
