### ISSUE TITLE
Add ability to change email address.

### ISSUE THREAD

**Issue by duckinator** [Gargron/mastodon#170]
Because I'm silly and used the wrong one when I signed up.

**Comment by Gargron** [comment]
Use [this form](https://mastodon.social/auth/edit)

**Comment by duckinator** [comment]
May be useful for that form to be linked to from somewhere else on the site. (Preferences page, maybe?)

**Comment by Euregan** [comment]
What if the problem is that you've registered with a wrong wrong email ? I actually registered using gmail.oom, so now I'm stuck without the ability to log in, because I can't receive the confirmation mail, meaning I can't change the mail. I could sign up again using the right address, but my username is already taken now :(

**Comment by fcayre** [comment]
@Euregan I'm having the same issue, have you found a solution?

**Comment by Euregan** [comment]
Alas ! No :(

**Comment by Gargron** [comment]
The solution is to e-mail your admin (contact address on /about/more page) and ask them to fix it for you or to manually confirm it so you can login with the wrong e-mail and then fix it yourself from the settings.

**Comment by Euregan** [comment]
Good to know, thanks !

**Comment by fcayre** [comment]
In my case, the email address is invalid, so the only solution is to email the instance's admin I guess. Thanks.

**Comment by ThisIsMissEm** [comment]
@Gargron would you be against a change which adds the ability to change email from admin panel? Presently having to do this via the CLI adds extra overhead — ideally we don't need to log into servers to perform minor account updates such as this.

**Comment by aprekates** [comment]
I got the same issue with another instance. I gave wrong email , and then i couldn create another account because the username was assumed taken!! Shouldnt that happen after a confirmation? Like a unified transaction ?
