### ISSUE TITLE
Drag and drop to upload photos

### ISSUE THREAD

**Issue by duckinator** [Gargron/mastodon#171]
I'm opening this on behalf of someone who mentioned it on Mastodon but didn't want to deal with GitHub.

What they want is the ability to drag and drop photos onto a part of Mastodon's UI to upload them.

Some information on drag & drop in JavaScript:

* https://css-tricks.com/drag-and-drop-file-uploading/
* http://html5demos.com/dnd-upload (demo)

**Comment by josefkenny** [comment]
It would be very useful if users could also upload photos by pasting them into the post text field from the clipboard. The Twitter website supports this (though TweetDeck does not), and I find it very useful for uploading screenshots.

Forgive me if I'm putting this in the wrong place, but it seems directly pertinent to drag & drop uploading.
