### ISSUE TITLE
What does "unlisted" mean? 

### ISSUE THREAD

**Issue by nevillepark** [Gargron/mastodon#172]
I assume it means one's statuses don't appear on the public timeline, but there isn't any explanation on the settings page or in the Github wiki. It would be good to add this to the documentation.

**Comment by Gargron** [comment]
It means "don't distribute posts to the public timeline" and it's a bit of a hack. Posts don't become private (hence not "private mode" or anything like that), they're just off the public timeline column.

**Comment by trwnh** [comment]
@josephkiranbabu Public timelines = local, federated, and hashtags.
