### ISSUE TITLE
Twitter-compatible api?

### ISSUE THREAD

**Issue by dequis** [Gargron/mastodon#176]
GNU social / StatusNet implement a subset of the twitter api, which allows existing twitter clients to work by changing the REST API base url ([example][1], [example][2])

http://skilledtests.com/wiki/Twitter-compatible_API

I haven't looked into this in depth but using the /api/v1/ base url doesn't seem to work. My client gets 404 when trying to hit `/api/v1/friends/ids.json?cursor=-1`

[1]: https://wiki.bitlbee.org/HowtoStatusNet
[2]: https://blogs.fsfe.org/samtuke/?p=539

**Comment by dequis** [comment]
I just noticed this FAQ entry https://github.com/Gargron/mastodon/wiki/FAQ#i-tried-logging-into-a-gnu-social-client-app-with-mastodon-and-it-didnt-work-why which somewhat addresses this.

It describes the current state, but does this mean you would be opposed to the addition of a compatibility layer for statusnet clients?

**Comment by Gargron** [comment]
Yes, I'm opposed to it. The API I came up with is a lot simpler and doesn't obscure the federated nature of things.
