### ISSUE TITLE
Control which notifications show up as desktop notifications

### ISSUE THREAD

**Issue by nex3** [Gargron/mastodon#182]
Currently if desktop notifications are available, *all* notifications show up there—including favs, which (if your toots are as rad as mine) occur very frequently and provide relatively little information. It would be nice to have some UI for choosing which notifications are surfaced as desktop notifications, like the one that currently exists for email notifications.

**Comment by hoodiek** [comment]
suggest merging into #244 and closing this issue to promote organization and lack of clutter.

**Comment by swaldie** [comment]
Taking @hoodiek's suggestion. Further comments on this issue can be made on #244.
