### ISSUE TITLE
OAuth2 rejecting "write" and "follow" scopes

### ISSUE THREAD

**Issue by nex3** [Gargron/mastodon#183]
If I make a request to `https://mastodon.social/oauth/authorize?client_id=$MY_CLIENT_ID&redirect_uri=$MY_REDIRECT_URI&response_type=code&scope=write`, I get a screen saying "The requested scope is invalid, unknown, or malformed." As far as I can tell from [the wiki](https://github.com/Gargron/mastodon/wiki/OAuth-details), this should work. If I use `scope=read` or omit the `scope` parameter entirely, it works as expected.

**Comment by nex3** [comment]
I figured it out: I needed to register the scopes with my OAuth2 app in order to request them for a given user. It would be nice if this were documented in the [app registration API docs](https://github.com/Gargron/mastodon/wiki/API#oauth-apps).

**Comment by Gargron** [comment]
Updated the wiki page.

**Comment by nex3** [comment]
Thanks!

**Comment by dereckson** [comment]
Where this procedure is now documented? I don't see it on the last archive.org snapshot of this page.
