### ISSUE TITLE
GIF avatar adds significant scrolling lag

### ISSUE THREAD

**Issue by jhauberg** [Gargron/mastodon#184]
This avatar causes significant scrolling lag for me in Safari, MacOS 10.12. I assume it's due to it being a GIF.

![screen shot 2016-11-22 at 11 35 29](https://cloud.githubusercontent.com/assets/1360637/20520698/42a11fb6-b0a8-11e6-833f-0bd560566799.jpg)

**Comment by jhauberg** [comment]
Further investigation shows that it is indeed a GIF, and at 9.8MB it's a sizeable one.

It also doesn't cause significant lag on the public profile page, only in the timeline.

**Comment by Gargron** [comment]
Wait, is it really 10MB? Avatar uploads are limited to 2MB, so how..?

**Comment by jhauberg** [comment]
I fetched the image from https://mastodon-social.s3-eu-central-1.amazonaws.com/accounts/avatars/000/010/843/large/coyote1.gif?1479761499 and it is 9.8MB on disk.

**Comment by Gargron** [comment]
I checked it with console/network in firefox. Size column: 1MB. Transferred column: 9.8MB. What?! I actually don't know how this works.

**Comment by jhauberg** [comment]
Sounds like a compression thing.

**Comment by Gargron** [comment]
Well! In any case, all avatars are now cropped to 120x120, which should not be an upscaling operation in most cases and be much gentler on bandwidth/CPU
