### ISSUE TITLE
API docs: Clarify what an array parameter means

### ISSUE THREAD

**Issue by nex3** [Gargron/mastodon#185]
The [API documentation](https://github.com/Gargron/mastodon/wiki/API) mentions that a few parameters (e.g. `media_ids` for `POST /api/v1/statuses`) are "arrays", but it doesn't define what that means in terms of raw HTTP.

**Comment by Gargron** [comment]
E.g. `?media_ids[]=1&media_ids[]=2&media_ids[]=3`

**Comment by Gargron** [comment]
Also ok, just added that to the API wiki
