### ISSUE TITLE
mastodon.social is offline

### ISSUE THREAD

**Issue by hach-que** [Gargron/mastodon#190]
I'm pretty sure you know about this and are working on it already, but just in case you don't have uptime checks on the service, it is completely offline right now.

Since the web servers are still responding with "We're sorry, but something went wrong.", my guess is either Redis or Postgres is down.

**Comment by inmysocks** [comment]
I am torn between being very sad that mastodon is down and being really happy that we got enough people to make the server crash.

**Comment by Gargron** [comment]
We're at max CPU/RAM here, I am currently provisioning an additional app server

**Comment by hach-que** [comment]
No worries - I did set up a status page people can look at https://stats.uptimerobot.com/0RQPNfJ95.  Once capacity is available again you might want to set up something at https://status.mastodon.social using Uptime Robot (which is a free service)

**Comment by inmysocks** [comment]
Are there stats on what is needed for running mastodon? Like could I have a tiny server on a raspberry pi to help with the load?

**Comment by hach-que** [comment]
I'm pretty sure I saw a chart floating around on Mastodon before that showed another instance's server using 8GB of RAM ;)

**Comment by Gargron** [comment]
It all depends on number of users because the real-time feature (ActionCable) basically keeps a connection up for as long as a person is online, and *that* scales really badly.

Yeah @hach-que in that case it's Neo4J eating the RAM which is 1) optional 2) Neo4J's default setting is allocating like 25% of the RAM straight away, in case of mastodon.social that's not the case

**Comment by hach-que** [comment]
Looks like it's back up - I'll file an issue for a status page and you can decide later if you want to set that up

**Comment by Gargron** [comment]
Current setup is as follows:

- 1 VPS with Postgres, Redis, Neo4J, that also runs a big chunk of the Sidekiq workers (background processing) and 1 process of the app
- 1 VPS with Nginx load balancing between the 1 app process on the other server and 3 app processes locally, plus a small number of Sidekiq workers

I'm adding one more VPS that will have only app processes

**Comment by hach-que** [comment]
Also if you want to and need assistance in setting up any kind of automated deployment or scaling of servers based on load, let me know as I've quite a bit of experience doing that on AWS.  (Though I'm also aware that auto-scaling might be undesirable since you're running it on your own dime)

**Comment by Gargron** [comment]
I'm not using AWS (except for S3), these are DigitalOcean droplets. So far it's been a combined $40/mo, new server will add a $10 on top of that.

**Comment by hach-que** [comment]
Ah okay (that's a good call, EC2 gets expensive quickly)

**Comment by Gargron** [comment]
What I *do* need help with is how to deal with assets. I don't want to include precompiled assets into the repository, I prefer generating them on production server. However, I only want to generate them on the app server that has nginx (since they will be served directly over nginx). I want other app servers to use those generated assets, and so far I'm halfway there by using an asset host. However, the other app servers don't link to the files with digests, because they're missing the sprockets json file in public/assets that contains the digests. So far I had to manually sync that file between app servers.

**Comment by hach-que** [comment]
Are you using any kind of build or deployment system to deploy out new versions of the code?  The right place to do precompilation of assets would be on a build server (after the code is checked out, before it's pushed out to the servers).

**Comment by Gargron** [comment]
No, no such thing currently. I ssh into all servers, pull from git, and restart the systemd services. Perhaps I should look into something like Capistrano, though configuration would need to be so generic that this repository doesn't just become source code of mastodon.social specifically.

**Comment by hach-que** [comment]
What I would do is have a private repository that has any "mastodon.social" specific stuff in it - SSH keys for example, as well as any server configurations, and throw a `Jenkinsfile` in that repository.  Get Jenkins to clone both the private repo and the public repo, and execute a deployment script you have the private repo which takes the source in the public repository and packages it up and deploys it out to your servers.

I have a Jenkins instance if you want to borrow it (this implies me having access to SSH keys since they'd be in a repo that the Jenkins instance could clone, and you're probably not comfortable with that)

**Comment by hach-que** [comment]
I'd also suggest that if your cluster starts getting any larger that you look into Kubernetes; that would allow you to use Docker for deployment, and Kubernetes manages rolling out updates without downtime (it also handles load balancing across multiple nodes with Nginx).
