### ISSUE TITLE
Add follow/unfollow buttons in lists of followers/following

### ISSUE THREAD

**Issue by psychicteeth** [Gargron/mastodon#195]
Especially at this early stage, it's good to be able to see who your friend are following and pick up on new contacts who just joined. At the moment you have to click through to each account and then click to follow; it would be nice to just have follow/unfollow (and maybe block?) in each user instance in the list, perhaps over to the top right. This would allow people to quickly follow or block users without having to load many individual user pages.

**Comment by Gargron** [comment]
There's a follow icon button next to the name in the lists?

**Comment by psychicteeth** [comment]
Ha, so there is. Was... did you just add that? Anyway, sorry - closing!
