### ISSUE TITLE
Text entry: up/down arrows do not work

### ISSUE THREAD

**Issue by psychicteeth** [Gargron/mastodon#197]
Mac OSX El Capitan, Chrome 54.0.2840.71 (64-bit)
The text entry box for toots does not support up and down arrows to move up and down lines text.

**Comment by egypturnash** [comment]
This happens on a Mac with Sierra and Safari 10.0.1 as well. Navigating around a multi-paragraph toot with nothing but cursor left/right and the mouse isn't fun.

Referring to "toots" in a bug report, however, is a lot of fun.

**Comment by LogicalDash** [comment]
Me too, Linux, Firefox 49.0.2

I don't think this is a browser-specific issue.

**Comment by jtpercon** [comment]
Same issue on Mac OS Sierra (running Firefox 50)

**Comment by Gargron** [comment]
Same root cause as #124, track progress there
