### ISSUE TITLE
Rename "Publish" to "Toot"

### ISSUE THREAD

**Issue by psychicteeth** [Gargron/mastodon#198]
You know it makes sense.

**Comment by TazeTSchnitzel** [comment]
Can this be a configuration option? I may or may not have a plan to eventually run a Mastodon instance which uses another name.

**Comment by IBPX** [comment]
This is already possible if you want to do it on your own site. All you need to do is edit [`/app/assets/javascripts/components/locales/en.jsx`](https://github.com/Gargron/mastodon/blob/master/app/assets/javascripts/components/locales/en.jsx).

```diff
-  "notification.favourite": "{name} favourited your status",
-  "notification.reblog": "{name} reblogged your status",
+  "notification.favourite": "{name} favourited your toot",
+  "notification.reblog": "{name} reblogged your toot",
```
_etc._

**Comment by Gargron** [comment]
It's done
