### ISSUE TITLE
Seperate repositories for Mastodon and mastodon.social issues

### ISSUE THREAD

**Issue by IBPX** [Gargron/mastodon#200]
I think there should be a separate repository for mastodon.social's issues (e.g. #175, #191), as mastodon.social is _not_ Mastodon, only an instance of it.

**Comment by Gargron** [comment]
#175 as I understand it would be a document included by default with the software, ideally customizable by instance admins. Anyhow, I'm not too keen to setup a new repository just for issues right now.

**Comment by TazeTSchnitzel** [comment]
As the biggest deployed instance, there's gonna be a lot of overlap for now.
