### ISSUE TITLE
https://mastodon.social/headers/medium/missing.png is 404

### ISSUE THREAD

**Issue by wchristian** [Gargron/mastodon#202]
For clickable: https://mastodon.social/headers/medium/missing.png

**Comment by Gargron** [comment]
I mean.. It's fine, it's just empty header image. Could make it a transparent pixel gif but I haven't had an issue with it 404ing

**Comment by wchristian** [comment]
It's fine as in, you don't mind it's missing, or it's not actually missing for you?

If you don't care about the file missing, then feel free to close, i guess. :)

**Comment by Gargron** [comment]
I don't mind the file missing
