### ISSUE TITLE
timed out ajax request resulted in error in console about being unable to parse html as json

### ISSUE THREAD

**Issue by wchristian** [Gargron/mastodon#203]
just had a call to https://mastodon.social/api/v1/statuses/145572/favourite return a 504 and the ajax in https://assets.mastodon.social/assets/application-5c84faecbe130d482fee99e5198a9ee0d77c14dd3b89b6ffcc0570369b8acc8e.js proceeded to complain about unable to parse the json, in the console.

**Comment by swaldie** [comment]
If you happen to encounter reproduction steps, please let us know.

**Comment by wchristian** [comment]
@swaldie No, I clicked favourite, the favourite ajax call to the url above failed to return useful json, your ajax didn't like it.

You will have to check your ajax calls for proper error handling callbacks.

**Comment by Gargron** [comment]
A timeout is an error. It comes from Nginx (the reverse proxy/load balancer) rather than the app/business logic. It can't serve JSON. In either case, an error message is displayed to the user, albeit the message recommends looking at the console to find out more which in this case might be confusing.

**Comment by wchristian** [comment]
It complained in the console. There never was an error shown.

**Comment by wchristian** [comment]
That means, unless you changed all of the ajax code to handle "can't deal with the non-json" to display a proper error, since 2016-11-22T17:44:20Z, this one might still lurk.

PS: Please ask before asserting about facts. :P
