### ISSUE TITLE
blank-tooting quite easy still

### ISSUE THREAD

**Issue by wchristian** [Gargron/mastodon#210]
A whole bunch of these can be used to blank-toot: https://www.cs.tut.fi/~jkorpela/chars/spaces.html

**Comment by TazeTSchnitzel** [comment]
Is this a bug or a feature?

**Comment by Gargron** [comment]
I'm not sure if this is bad. If you want to blank-toot.. Why not. Up for your followers to decide if they like it, no?

**Comment by wchristian** [comment]
Well you have *some* protection against it?

Anyhow, i have no opinion, if you'd like to keep that as a hidden feature that's fine with me, and with this, documented. :)

**Comment by dieseltravis** [comment]
⠀
