### ISSUE TITLE
chrome notifications not clickable

### ISSUE THREAD

**Issue by wchristian** [Gargron/mastodon#212]
i'd expect it to get me to the mastodon tab maybe?

**Comment by Gargron** [comment]
That's not controlled by JS

**Comment by wchristian** [comment]
Err?

https://developer.chrome.com/apps/notifications#event-onClicked

**Comment by Gargron** [comment]
Yes but I don't control which tab is focused from the tab's JS

**Comment by zcdunn** [comment]
You can focus the tab using the [Clients](https://developer.mozilla.org/en-US/docs/Web/API/Clients) interface from within a ServiceWorker.

**Comment by Gargron** [comment]
We don't use service workers at all atm

**Comment by jbond23** [comment]
From a user perspective this is confusing. I get the notification popup window in the bottom right corner of the screen, but I can't do anything with it. It's a very natural reaction to want to click on it and be taken to the source of the notification. Is there really no way to achieve this?
