### ISSUE TITLE
Ability to change usernames

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gargron/mastodon#214]
I have a feeling this is probably tricky to do under the GNU Social protocol.

**Comment by nex3** [comment]
This could potentially be covered by #177.

**Comment by TazeTSchnitzel** [comment]
Good point. Changing handle on one instance is essentially a migration within an instance.

**Comment by swaldie** [comment]
I'm going to reference this to #177 and close it for now then.

**Comment by cknoll** [comment]
maybe it is worth mentioning the "Move to a different account"-Feature here (almost at the bottom of the edit-profile-page).

Description states: "If you wish to redirect this account to a different one, you can configure it here."
