### ISSUE TITLE
Pages for posts and users only allow limited interaction

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gargron/mastodon#216]
The main interface for Mastodon is that TweetDeck-like thing, but there's also individual Web Twitter-style pages for individual users and their posts. They don't let you interact at all beyond following them, though. Adding favourite, retweet, reply, and possibly also block and mention options to them would give you a choice of interfaces (and avoid having to hunt for the same post in the main interface if you want to interact).

**Comment by DeeUnderscore** [comment]
See also #174

**Comment by TazeTSchnitzel** [comment]
Oh, my bad, I must have missed that one. This is basically a duplicate of that.

**Comment by swaldie** [comment]
Marking this as duplicate and closing.
