### ISSUE TITLE
mastodon_web won't run correctly after finishing setup steps in Readme

### ISSUE THREAD

**Issue by andrewmichaud** [Gargron/mastodon#218]
I've followed the steps in the Readme to set up my own Mastodon instance.
1) Installed Docker, docker-compose.
2) Copied .env.production.sample to .env.production. Set DB_PASS, LOCAL_DOMAIN, SMTP_SERVER, SMTP_LOGIN, SMTP_PASSWORD, SMTP_FROM_ADDRESS to valid values. (I didn't originally set DB_PASS, and wasn't sure if it needed to be. I saw the same issue regardless.)
3. Ran the docker commands listed in the Readme
```
docker-compose build
docker-compose up -d
docker-compose run --rm web rails db:migrate
docker-compose run --rm web rails assets:precompile
```

The postgres, redis, and mastodon_neo4j containers seem to be running fine. mastodon_web and mastodon_sidekiq keep crashing. What I'm seeing when I attach to mastodon_web is:
```
=> Booting Puma                                                                                                                                
=> Rails 5.0.0.1 application starting in production on http://0.0.0.0:3000                                                                     
=> Run `rails server -h` for more startup options                                                                                              
Exiting                                                                                                                                        
/mastodon/vendor/bundle/ruby/2.3.0/gems/devise-4.2.0/lib/devise/rails/routes.rb:498:in `raise_no_secret_key': Devise.secret_key was not set. Please add the following to your Devise initializer: (RuntimeError)
```
There's more message, but it mentions secret_key and I wasn't sure if I should be sharing that.

I assume I've just missed something in the setup process. Any idea what?

**Comment by Gargron** [comment]
Did you not set

```
PAPERCLIP_SECRET=
SECRET_KEY_BASE=
```

You can use `rake secret` to generate a random string for each

**Comment by andrewmichaud** [comment]
do they just need to be two different random secret things?

**Comment by Gargron** [comment]
Yep

**Comment by andrewmichaud** [comment]
That worked!

I have a different question now. I can move it to a different issue if I need to.
What do I need to do to wire my mastodon up to my domain? I have it running on a box attached to the domain I want. Do I need nginx in front of it or something to make sure ports are connected correctly?

**Comment by Gargron** [comment]
Yep I suggest using nginx. You can get a free certificate with let's encrypt and use SSL as well.

**Comment by andrewmichaud** [comment]
I got it up and running. Thanks for your help!
