### ISSUE TITLE
I want this to grow but I think it needs a few things...

### ISSUE THREAD

**Issue by XDChunk** [Gargron/mastodon#220]
1. Change Publish to Toot.
2. Add DMs
3. Add Verification
4. Be able to post Videos
5. Mute people from the Public TL
6. Add user columns
7. A mobile app

I don't know how hard it would be to put these together but I really hope they are added.

**Comment by hach-que** [comment]
As a summary based on a third-party whose observed some things:

1. Well.. this is done :P
2. There's a proposal for implementing DMs spec-wise here: https://github.com/Gargron/mastodon/pull/224
3. I'd guess this is a while off - verification requires a team of people to actually manually verify accounts.  Even then, it would only be verified accounts on the main Mastodon instance.
4. I'm pretty sure this is already possible?  I'm pretty sure I saw videos in the public feed earlier.  It might _not_ be possible in the Mastodon UI though...
5. You can block accounts already, is there a difference between muting and blocking?
6. I'd like to see this too, but someone needs to build it
7. I think some people are working on this, but it's still early days.  If you're on Android and have Chrome installed "Add to Home Screen" actually gives a really nice experience with notifications and everything.

**Comment by Ragzouken** [comment]
please let's not have verification

**Comment by odetomyday** [comment]
Verification seems too hierarchical for the politics of the site. But as for #5, the block function is pretty buggy, and blocking someone doesn't keep you from seeing their content through re-blogs, right?

**Comment by Gargron** [comment]
>blocking someone doesn't keep you from seeing their content through re-blogs, right

It does (at least it should, if it ain't so, let me know. although i also heard about a bug where reblogs don't get removed from home on unfollow, this might be related)

Verification would essentially be "do you trust the person running this instance to actually verify this person't identity?" I think it might be better if keybase.io implemented OStatus verification

**Comment by nex3** [comment]
Federation could also be used for domain-based verification. If my handle is @nex3@nex-3.com, you can be pretty confident that I'm me.

**Comment by hoodiek** [comment]
i would suggest this issue be closed, as it is very off topic and should be better managed through individual issues for many of the requests. some points to note:

-DMS have been decided to not currently be involved as a goal for mastodon
-publish is already toot
-verification seems to have been shot down as an idea, which i personally would agree with
-videos can be posted
-users can be muted (although it is still called blocked) from within the public timeline column, and even if the syntax and wording used here means that they should be able to be manually muted in a way that is not a block, that belongs in thread #231 as it has become the super post for muting and blocking tools
-user columns need their own topic with more extensive communication about what it entails
-apps are in progress, and are maintained by other users, such as https://github.com/jeroensmeets/mastodon-app this github project.

thank you for reading.

**Comment by swaldie** [comment]
Yeah I think this is all covered by other issues or can be brought up individually at this time.
