### ISSUE TITLE
Avatar fails to load, HTTP error 403

### ISSUE THREAD

**Issue by Spexfox** [Gargron/mastodon#228]
My avatar has suddenly stopped appearing. This occurred after I added an emoji to my display name as the first character. Specifically, the rose (🌹). Checking the Chrome web dev console shows a HTTP 403 error when trying to load the resource.

It's unknown if other users experience a 403 error when trying to load my avatar.

The issue does not resolve with:
- A "hard refresh" (Ctrl+F5)
- Uploading a new avatar
- Removing the emoji from the Display Name 

The issue does resolve with:
- Toting a Toot.
-- _This is only temporary. The issue returns after following a user or otherwise triggering an event that reloads the resource. Or by reloading the entire page._

This issue does **not** appear to impact the static user profile page or individual static Toot pages.

Error | Resource
------------ | -------------
Failed to load resource: the server responded with a status of 403 (Forbidden) | https://mastodon-social.s3-eu-central-1.amazonaws.com/accounts/avatars/000/013/416/large/PSX_20161123_001955.jpg

Reproduction Steps:

1. Navigate to the Profile Settings page. (https://mastodon.social/settings/profile)
2. Enter a rose (🌹) emoji as the **first character** of the _display name_.
3. Click "Save Changes"
4. Return to the Toot Deck (yes I'm calling it that) (https://mastodon.social/)
5. Perform a "hard refresh" with Ctrl+F5 to ensure no caching issues.

Reproduced 2 out of 2 times.

**Comment by hoodiek** [comment]
this seems to have been resolved, or at least is not something i can recreate following your steps. might have been resolved when swapping to the new image hosting.

**Comment by swaldie** [comment]
Yeah, can't repro this anymore, calling it fixed.
