### ISSUE TITLE
Separate Follow/Unfollow and Block buttons

### ISSUE THREAD

**Issue by orbitcube** [Gargron/mastodon#230]
As it is now, the Follow (or Unfollow) and Block buttons are right next to each other in the dropdown menu. I personally think they should a little bit more separated so it's harder to accidentally click one or the other.

**Comment by TazeTSchnitzel** [comment]
Do we ask for confirmation first? If not, that would also deal with this. Could be as simple as a `prompt()`.

**Comment by orbitcube** [comment]
I think a block confirmation prompt would be a fine solution, yeah.

**Comment by Gargron** [comment]
The follow button is now outside the dropdown
