### ISSUE TITLE
individual posts should be able to be unlisted, through a toggle when posting

### ISSUE THREAD

**Issue by hoodiek** [Gargron/mastodon#233]
it's in the title. right beside the toot button you could put it. thank you for listening.

**Comment by grimedango** [comment]
This would would be a phenomenal feature, awesome input!

**Comment by hoodiek** [comment]
i believe there is another thing that can be done for accessibility sake: the checkbox could retain it's checkedness between sessions. ie: if you close the site and reopen: the checkbox would still be checked if it was when you closed it

**Comment by hoodiek** [comment]
update/new thought! the easiest way to resolve this issue is to bring back the settings listed or unlisted with the title "default publicity" or the like, to allow the user to select what to default back to
