### ISSUE TITLE
Disable the user's page when unlisted

### ISSUE THREAD

**Issue by LogicalDash** [Gargron/mastodon#234]
A user in unlisted mode, which keeps them off the public timeline, probably doesn't want their toots visible to the entire world, yet currently they still have a /user/ page that even logged-off people can see. Unlisted users' timelines, and all toots therein, should only be viewable by logged-in users.

**Comment by LogicalDash** [comment]
Creepers have a habit of logging off to hate-read the Twitters of people who have blocked them. This proposal would at least require them to make a new account to do this. Further discouragement would require something like Twitter's private and protected modes, with more granularity, but that would be a big project; hiding unlisted users from the public seems easy.

**Comment by lauramichet** [comment]
I do want my toots visible on a user page, but I don't want them on the public timeline. I think there should be separate settings for hiding your account from the world and hiding it from the public timeline

**Comment by TazeTSchnitzel** [comment]
Because Mastodon is federated – that is, instances are part of the wider network – such pages need to be public for other instances to be able to see them.

So what you're proposing would effectively disable federation for a particular user.

That being said… you could choose to make search engines not index a user's content if they've chosen that option…?

**Comment by Gargron** [comment]
I can probably close this as resolved since private toots don't appear on public profiles, and unlisted mode is just for unlisting from public timeline, not from the public record overall.

**Comment by TazeTSchnitzel** [comment]
I still think an option to avoid search engine indexing would be useful. Should I make a separate issue for that?
