### ISSUE TITLE
Sensitive content isnt hidden when looking at it from users/username

### ISSUE THREAD

**Issue by radian2pi** [Gargron/mastodon#237]
on here: https://mastodon.social/users/radian2pi

Metroid Other M should be hidden, but isn't.

**Comment by hoodiek** [comment]
this seems to have already been resolved for me. is this something already addressed? if not we need to do research to find the specific use case to recreate the bug so it may be fixed. if it IS fixed it can be closed

**Comment by radian2pi** [comment]
in this screen it hides the image:
![workshere](https://cloud.githubusercontent.com/assets/12741223/21236879/49b18d82-c2c2-11e6-9735-7e937b7f94c5.PNG)

but for me, on this screen it doesnt:
![doesntworkhereforme](https://cloud.githubusercontent.com/assets/12741223/21236888/559c436c-c2c2-11e6-8344-7d6c814921fc.PNG)
 
Unless showing my own "sensitive content" is the intended behavior on the larger screen...

**Comment by hoodiek** [comment]
aha yes, i missed this, this is indeed a bug, thank you for explaining to ensure it stayed  open!
