### ISSUE TITLE
Thread resolving for remote statuses

### ISSUE THREAD

**Issue by Gargron** [Gargron/mastodon#24]
In `ProcessFeedService`, if a remote status we want to save (A)  is a response to another status (B), then we try to look up a local copy of B. If it fails, no reply-to information is saved.

It's up for debate if the method should then try to somehow fetch the B status. The potential problem with that approach would be that B is a reply to status C, etc etc indefinitely, which would force the Mastodon service to crawl the entire fediverse. That may not be wise.

**Comment by AltaV** [comment]
If the relation of A to B can be saved and B can be resolved through the federated API, then B and C and so on could be left to the consuming interface.

Although, there may others be issues with resolving a thread specifically in resolving only one branch of a potentially large conversation tree.
