### ISSUE TITLE
Figure out what (if anything) to do about GNU Social's nickname normalization

### ISSUE THREAD

**Issue by DeeUnderscore** [Gargron/mastodon#246]
GNU Social normalizes nicknames by [lowercasing them and removing underscores](https://git.gnu.io/gnu/gnu-social/blob/master/lib/nickname.php#L119-122), while in Mastodon, underscores in usernames are significant when it comes to differentiating usernames. This means that `@u_n_d_e_r_s_c_o_r_e_s` and `@underscores` are the same thing on a GNU Social instance, but not the same thing in Mastodon. 

From what I've seen, Mastodon toots federated on GNU Social instances will appear with names normalized (using GNU Social's normalization). Profile URLs will be correct, and replies appear to go the right place—notifications on Mastodon appear to go to the right person.

I imagine there are some problems that may occur here, so some more testing may be in order to figure out if stuff may go to unintended recipients in some cases.

**Comment by Gargron** [comment]
I have no clue why GS decided to do it this way. Do GS-side mentions of our users with underscores work? Or does it try to mention the underscore-less version? Either way wouldn't be our bug

**Comment by DeeUnderscore** [comment]
Well, as far as I can tell, it fetches profile links and everything correctly (presumably via webfinger). In the actual text of the notice, stuff is normalized so underscores are gone, but links are correct.

As to whether or not mentions actually reach intended recipients... well, I tried it from gnusocial.no, and have no idea if it failed because of name normalization, network, or other reasons, considering the notice is not visible from mastodon.social at all.

**Comment by Gargron** [comment]
I'm just gonna close this since I don't see it as us doing anything wrong
