### ISSUE TITLE
Profile caching overrides new profile info for a time

### ISSUE THREAD

**Issue by Skirmisher** [Gargron/mastodon#248]
To reproduce, simply change any part of your profile info (name, bio, avatar, header) and view your profile from the Mastodon home page. The new info will appear initially, but will be replaced with the old info as the rest of the content loads. This persists for at least an hour or two, and hard-refreshing makes no difference. However, viewing the profile permalink as a separate page reflects the changes instantly.

When the profile issue occurs, all instances of the avatar in other timelines become replaced with the old avatar. However, opening one of the user's toots restores their new avatar.

Hard-refreshing may flush the old avatar, resulting in a broken image whenever it is referenced.

**Comment by Gargron** [comment]
Old account is cached along with statuses, as statuses load, the data that is loaded more recently replaces the older (but actually newer) data.
