### ISSUE TITLE
Mobile profile view has no room for toots

### ISSUE THREAD

**Issue by triplefox** [Gargron/mastodon#257]
For example: https://mastodon.social/media/13730

Twitter app's behavior in this instance is to make the profile scroll out.

**Comment by unsmell** [comment]
here's a screenshot for reference
![screenshot_20161124-160641](https://cloud.githubusercontent.com/assets/2267475/20606378/0c4f67a6-b260-11e6-80fd-b6b0e9b42aa4.png)

**Comment by Gargron** [comment]
Ideally we need more Responsive Design :tm: but I'm a terrible person who uses inline styles in React.js so fml

**Comment by Gargron** [comment]
Duplicate of #196, track progress there
