### ISSUE TITLE
Un-reposting is broken

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gargron/mastodon#258]
Now it just tries to re-repost, which of course fails.

Probably caused by https://github.com/Gargron/mastodon/commit/cbc50016eb3d0a46e76aca9ed199b036ce20abdb

**Comment by Gargron** [comment]
Is this consistent behaviour? Are you sure you didn't try unreblogging before the actual request in the background completed?

**Comment by TazeTSchnitzel** [comment]
It seems to be. The icon will change back to grey, yet it gives a `422 Validation failed: Reblog of status already exists` error.

**Comment by Gargron** [comment]
Try waiting until the progress bar completes. Usually people don't unreblog/unfav something instantly after reblogging/faving, the benefit of instant feedback there is more useful

**Comment by TazeTSchnitzel** [comment]
Oh, un-reblogging does still work, apparently. I guess it was indeed lag. My bad.
