### ISSUE TITLE
What's port 7575?

### ISSUE THREAD

**Issue by alyssais** [Gargron/mastodon#259]
I've been trying to set up a development environment for Mastodon, and I'm just wondering why rails_helper.rb whitelists port 7575 with Webmock? Is that Neo4j?

**Comment by Gargron** [comment]
Yes that's Neo4J. But I'm like, super considering getting rid of Neo4J. I had it disabled on mastodon.social in the past few days and nobody complained about lack of follow suggestions. What do you think?

**Comment by alyssais** [comment]
I quite liked the follow suggestions, but they're not super critical. Don't think it's worth a lot of effort.

Is there a reason it was on 7575 instead of the default 7474?

**Comment by Gargron** [comment]
You usually run tests from the same machine as you do development from. You don't want the tests to overwrite the "proper" database.

**Comment by alyssais** [comment]
Oh, of course.
