### ISSUE TITLE
Toots can exceed character limit.

### ISSUE THREAD

**Issue by BHoney** [Gargron/mastodon#263]
Hello, I noticed that the Toot character limit doesn't seem to be actively enforced, as discovered with [this toot](https://mastodon.social/users/bloodyhoney/updates/189694).

The toot in question is 537 characters, but I didn't receive any error when I pushed send. I can try to replicate it and report back if necessary.

**UPDATE**: After testing a few other posts, it seem this toot was able to bypass the count by using the excess 37 characters for emoji.

**Comment by Gargron** [comment]
I'm assuming that somewhere along the line some character count is wrong because iirc emoji utf-8 are multibyte aka multiple characters. It could be that the JS character counter counts one emoji as multiple characters due to that, since iirc ruby support for utf-8 is perfect

**Comment by DeeUnderscore** [comment]
As far as I can tell, the JS counter counts UTF-16 code units, so emojis tend to count for 2 characters, while two byte UTF-8 counts as 1.

**Comment by Gargron** [comment]
Confirmed:

    "💦".length
    > 2

**Comment by TazeTSchnitzel** [comment]
Yes, that's one issue. Another to consider is Unicode normalisation. You should decide on which normalisation form to use for character counts, if you haven't already. Twitter uses NFC: https://dev.twitter.com/basics/counting-characters

**Comment by Gargron** [comment]
I think this actually doesn't matter that much, an edge case that is harmless since, well, other software lets you post much longer posts anyway, so a few characters over 500 wouldn't be a an issue, especially considering it doesn't really let you post more, it's just the JS counter is a bit wrong with emojis.
