### ISSUE TITLE
Resizeable text box

### ISSUE THREAD

**Issue by pisss** [Gargron/mastodon#267]
We write big posts sometimes! Let's have a big ol' box, to look at our big posts.

**Comment by unsmell** [comment]
use this userstyle
```textarea {
    resize: vertical !important;
    max-height: 25em !important;
}```

**Comment by hoodiek** [comment]
@Gargron this post can be closed now, just since it's something that can be easily done i'm tagging you in

**Comment by unsmell** [comment]
I don't know when it was changed, but the current text box has `resize: vertical` without any userstyles
