### ISSUE TITLE
Toggle for post-to-public

### ISSUE THREAD

**Issue by triplefox** [Gargron/mastodon#268]
Folks are looking for a fast switch between home and public. The simplest way to do this is to add another toggle just like "sensitive". (If we end up with a lot of these posting configuration modes we may need a UX reflow later, but I think trying it out is worthwhile)

**Comment by triplefox** [comment]
Also if we go down this path, the UX should encourage starting with public on so that our newbie welcome wagon can continue.

**Comment by hoodiek** [comment]
this has already been suggested with #233
