### ISSUE TITLE
Unforgiving image previews 

### ISSUE THREAD

**Issue by triplefox** [Gargron/mastodon#269]
Everyone's nicely cropped images end up with an awkward middle cut in timeline preview. What could be done about this? An image formatting configuration? Some kind of recognition magic?

**Comment by nclm** [comment]
For the “recognition magic”, there’s a JS library: https://github.com/jwagner/smartcrop.js

**Comment by Gargron** [comment]
They're not technically cropped, the images are resized to a smaller size without cutting anything off, but the previews in the UI are essentially fixed-size divs that set the background to the image and center it. Using a machine learning library to crop them client-side would be overkill

**Comment by triplefox** [comment]
Here is something people also consistently get wrong: When adding 2+ images to their toot they expect RTL order and get LTR.

**Comment by marrus-sh** [comment]
Something related to this that I believe would help is fixing the aspect-ratio for image previews—for example, Twitter image previews are all 2:1. This doesn't help with regards to the positioning of the image, but it does help users ahead-of-time know what part of the image would be visible. (Importantly, if users crop their image to match the preview aspect-ratio, the whole image is displayed).

**Comment by Gargron** [comment]
I think I'm gonna close this since I can't do much about it. The sizes are more or less consistent:

- 110px high in timeline view, 300px high in detail view (halved when there's more than 3 images)
- width is fluid, in columns it's around 300px (halved when there's more than 2 images), in public view at most around 700px (evenly divided between all images)

**Comment by deutrino** [comment]
I would like to ask for this to be re-opened. The cropping is awkward, looks bad, and causes people to have to click on things which they could have just read in their timeline(s) without clicking (small comics, memes, image macros). I strongly believe that fit-to-width is a better idea, though a compromise checkbox would make me happy.
