### ISSUE TITLE
Allow public access and "permalinks"

### ISSUE THREAD

**Issue by Thann** [Gargron/mastodon#270]
Could the web ui work for users who are not signed in?
It would be nice when sharing links other sites and is a feature of most, if not all, social media sites. Also maybe slightly shorter or nicer URLs could be implemented at the same time. IDK if you have any plans for doing something like this yet, but I wouldn't mind putting in the leg work to make this happen =]

**Comment by Gargron** [comment]
Clicking on date/time of status in the web UI will take you to the public page (permalink). Similarly, opening profiles in a new tab will open the public version, alternatively clicking on the avatar/username on an opened profile also takes you to the public version.
