### ISSUE TITLE
Clicking "Home" should reset Mastodon

### ISSUE THREAD

**Issue by Zarkonnen** [Gargron/mastodon#272]
For weird brain reasons, I get itchy when I can't easily reset the GUI of something to a default/starting state. If I select a hashtag to be shown in the rightmost pane, I can find no way to get rid of that again without manually editing the URL to be https://mastodon.social/.

Could you make the Home icon on pane 2 go to https://mastodon.social/ ?

**Comment by Gargron** [comment]
"Home" in that case means "home feed" aka "people you're following", it doesn't have anything to do with being the homepage.

See also: https://github.com/Gargron/mastodon/issues/262

**Comment by Zarkonnen** [comment]
Ah, good point. :+1:
