### ISSUE TITLE
Mark as read

### ISSUE THREAD

**Issue by triplefox** [Gargron/mastodon#274]
This would be equivalent to the "clear" in Tweetdeck: it resets the column to the top and either eliminates the old stuff or puts a visible reading marker on it so that you can find your place.

**Comment by Thann** [comment]
This could be done entirely client-side I think

**Comment by hoodiek** [comment]
recommend this be closed as per #244 addition of a button to mark column as read and flush it of notifications

**Comment by swaldie** [comment]
I generally agree with @hoodiek's suggestion here, but I also want to make sure that this doesn't apply to other UI elements as well before I close this one.

**Comment by hoodiek** [comment]
i dont quite understand here, by "other UI elements" do you mean the other toot columns?

**Comment by hoodiek** [comment]
i could add a note in the other one that the flush icon should go on every column, not just notifications, and rename the issue to accommodate

**Comment by swaldie** [comment]
Whoops, yeah, sorry, I should have been more clear. I think this issue can probably stand alone if they want it in all Toot columns, but if this is specifically about notifications, I agree it should be consolidated into #244.

**Comment by hoodiek** [comment]
since this has been left be for a week, and no answer from the original poster, i would suggest closing it for now to avoid clutter in the issues queue

**Comment by swaldie** [comment]
Yeah this will be closed and can probably be referenced into #244 if it needs to be brought up again.
