### ISSUE TITLE
minor ux: don't auto-scroll timelines if the mouse is hovering inside them

### ISSUE THREAD

**Issue by Ragzouken** [Gargron/mastodon#277]
i keep misclicking because toots move underneath my mouse as i'm clicking

**Comment by Thann** [comment]
I think a general solution to this would be instead of auto-adding new toots, just tell you at the top that there are new ones, and clicking it will scroll to top and show the new ones.

**Comment by swaldie** [comment]
This is similar enough to #38 that I'm going to add the comment there and close this as a duplicate.
