### ISSUE TITLE
Profile informations not fully federated to GNUsocial

### ISSUE THREAD

**Issue by tchncs** [Gargron/mastodon#283]
I just saw, that my profile description and background image is in an outdated state/missing on GNUsocial.de.
The tiny icon to actually view the profile is also missing.

![2016-11-25-194532_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/20633579/8fa27b14-b348-11e6-93e7-65cea0f1f352.png)

Didn't saw any issue about it, hope it is not a duplicate. :)

**Comment by Gargron** [comment]
Known GNU social bug, unfortunately. https://git.gnu.io/gnu/gnu-social/issues/164

**Comment by Gargron** [comment]
https://git.gnu.io/gnu/gnu-social/issues/165

**Comment by tchncs** [comment]
Ah i see, so lets close this, then. :)
