### ISSUE TITLE
Follow icon state in the Notifications column

### ISSUE THREAD

**Issue by nclm** [Gargron/mastodon#285]
There are five notifications about people that are now following me in the column. I follow all of them. They all have the Follow/Unfollow icon in the notification. Only one icon took into account the fact that I follow the person back, and is in the ‘Click to unfollow’ (blue) state. The four others are ‘Click to follow’ (grey) which I do already.

By the way, I think the colours should be reversed. Blue to follow (it is a positive action, an invitation), grey to unfollow (more rare, only when you change your mind, can be more discreet).

**Comment by Gargron** [comment]
I fixed it this way: the follow/unfollow button stays hidden until the actual state is loaded, avoiding confusion. Regarding colors, I disagree - inactive elements should not distract the user's attention. The color is there to signify what the user has already interacted with. Besides, changing the rules now would confuse a lot of people.
