### ISSUE TITLE
Moderation tools

### ISSUE THREAD

**Issue by vonWolfehaus** [Gargron/mastodon#287]
Thank you very much for building this platform! I know how much work it takes and I sincerely appreciate it.

Since this is an open social system, there needs to be something besides "shadowblocking" to handle harassers and other abusive users, or the platform has a good chance of devolving into a cesspool.

Some suggestions:

- whitelisting servers that have vetted users (a trust-based network, where users outside cannot see posts from these servers and _vice-versa_)
- crowd-sourced moderation tools such as filtering (auto-block new users with fewer than X posts; auto-block users who only post links; etc)
- able to report abusive posts which are then reviewed by mod panels composed of randomly-chosen users (users opt-in to be mods and judge posts that have been marked as abuse, with enough votes getting the user banned - this is how OkCupid deals with their mountain of bad apples)

This is just a few ideas, each having their pros/cons, but there's also other ideas from people much smarter than me. I don't like Ruby but I'm familiar with the frontend (day job) so I can help implement, since I'm quite passionate about this topic. Thanks for considering.

**Comment by grimedango** [comment]
I like the jury concept for moderation

**Comment by swaldie** [comment]
A lot of these seem related to or would be included as part of #17. I'm going to relate your issue there and close this for now.
