### ISSUE TITLE
Typing external instance handles beginning with @ into search bar prevents lookup

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gargron/mastodon#288]
If you type `@foo@example.org`, Mastodon will try to look up the user `@foo` on `example.org` and fail, rather than `foo` on `example.org`.

**Comment by Gargron** [comment]
Ohhhh. Good observation.

**Comment by TazeTSchnitzel** [comment]
Viewing the log while the site's in use is interesting and it's how I discovered this was happening.
