### ISSUE TITLE
Pinned toots

### ISSUE THREAD

**Issue by triplefox** [Gargron/mastodon#306]
Twitter allows you to pin a tweet to the top of your timeline in profile view. This is often used for a long-term advertisement or informational posting.

**Comment by haniawni** [comment]
This is particularly important for activists, as it affords them the option of a billboard-like list of endorsed projects, highlighting particularly important issues/events, or explanations of their ideological alignment. This demographic is also most at risk for material consequences for Twitter's sale of their data to mercenaries or the like, as seen in #NODAPL and elsewhere.

**Comment by TazeTSchnitzel** [comment]
Er, but you could also put that sort of info in your bio, @haniawni.

**Comment by TazeTSchnitzel** [comment]
I wonder if any sites in the fediverse have implemented this, and what approach they took to it. If so, we should probably copy their approach for interoperability.

**Comment by marrus-sh** [comment]
Also throwing my support behind this. Bios are short and pinned toots can be long. Pinned toots are also super helpful for indie artists who are trying to self-promote; the most important quality of a pinned toot is **it can be boosted by other tooters** (unlike a bio which cannot be interacted with).

No idea if this has been implemented elsewhere before, but I would imagine adding something like
```json
"urls": [
    {
        "value": "https://mastodon.social/users/marrus_sh/updates/312820",
        "type": "pinned"
    }
]
```
to the Portable Contact for a given user would be the easiest way? The question would be what value to use for `type`.

**Comment by hoodiek** [comment]
i'm going to suggest we merge this with #232 to allow less clutter over the issue basically being identical: a lack of space in bio. i will add a note that pinned toots are also a good thing to add, and will copy relevant information such as @marrus-sh's code example to the other post.

**Comment by swaldie** [comment]
Agreed. We'll include discussion of pinning a toot in #232 from now on.
