### ISSUE TITLE
Videos autoplay (iOS)

### ISSUE THREAD

**Issue by mynatt** [Gargron/mastodon#308]
I've noticed that videos (in your home timeline or the public timeline) will automatically play on iOS Safari when loaded for the first time, whether they're onscreen or offscreen. This also happens when they're shown again by navigating _back_ to a timeline from, for instance, a user profile. This is very clearly a bug, as they will halt navigation and expand to fill the screen whether they're interacted with or not, will play sound at the current device volume, and then need to be dismissed.

**Comment by Gargron** [comment]
Videos no longer autoplay now that they display a preview image with a play button instead.
