### ISSUE TITLE
Ability to track hashtags in separate column without overriding other columns

### ISSUE THREAD

**Issue by mkosler** [Gargron/mastodon#310]
Currently, if I attempt to track a hashtag, it takes over the fourth column. However, this fourth column is multi-use, such as for expanding a toot or viewing the public timeline. It would be nice to have the ability to create additional columns for hashtag tracking that don't interfere with other columns.

This is totally an enhancement, by the way. Don't think I can tag it myself.

**Comment by swaldie** [comment]
I'm going to reference this issue in #351 since that's a more general version of this enhancement request and then close this one.
