### ISSUE TITLE
Boosted posts cannot be removed from own feed

### ISSUE THREAD

**Issue by ben0o** [Gargron/mastodon#312]
If you boost a post but later decide that you no longer wish to do so for whatever reason, there isn't an option to go back and remove it from your own timeline.

You can go back and block the user you previously boosted but all this does is hide that users posts from your own feed, NOT delete them.

**Comment by Gargron** [comment]
You mean un-boosting doesn't work?

**Comment by ben0o** [comment]
Closed: user error. I didn't notice the boost button was a toggle. I was trying to find an unboost option in the elipses dropdown menu.
