### ISSUE TITLE
Provide prebuilt Docker image on Docker Hub

### ISSUE THREAD

**Issue by alexgleason** [Gargron/mastodon#313]

**Comment by Gargron** [comment]
Done! https://hub.docker.com/r/gargron/mastodon/

**Comment by alexgleason** [comment]
Fantastic, thank you!

**Comment by alexgleason** [comment]
Note that it might be easier for you to configure an [automated build](https://docs.docker.com/docker-hub/builds/) for Docker Hub so you don't have to manually push up new images for each new version.

**Comment by Gargron** [comment]
Yeah, it's an automated build!
