### ISSUE TITLE
Display public feed upon login

### ISSUE THREAD

**Issue by alexgleason** [Gargron/mastodon#314]
For new users, the public feed is both the most important feature as well as the most difficult to discover. The public feed is part of what makes Mastodon so effective compared to other GNU Social platforms because it throws the user right into a format that's nearly a live chat. The high-speed interactions are a brilliant UX and should not be hidden from the user.

**Comment by marrus-sh** [comment]
I think this would be convenient for a lot of users but I also know some folks don't like seeing the public feed, so if implemented this should probably be controlled via a preference. Issue #262 is related.

**Comment by swaldie** [comment]
Yeah I'm going to reference this to #262 and close it for now, and we'll use that as the main issue for "The Public Timeline Needs to be more easily discoverable"
