### ISSUE TITLE
Document serving static files in production

### ISSUE THREAD

**Issue by alexgleason** [Gargron/mastodon#319]
**EDIT:** My first question has been answered, but it should be documented.

~~~Hi again, I've gotten much further in setting up my Mastodon instance. The only issue now is that static files aren't being served. Is this handled by Rails or do I need to set up an Nginx reverse proxy to handle that? The documentation stops with using docker-compose so I assumed that was it. Wanting to know if that's the case before I proceed.~~~

Thanks!

**Comment by alexgleason** [comment]
@triplefox did you happen to see if anyone commented after me on IRC? I had to close my laptop and I can't see old logs there

**Comment by alexgleason** [comment]
Okay I think I answered my own question,

from `mastodon/production.py`

```
  # Disable serving static files from the `/public` folder by default since
  # Apache or NGINX already handles this.
  config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'].present?
```
Whew, okay.

So, there is still a problem here, though. The documentation should note this.

**Comment by Gargron** [comment]
It is preferrable for Nginx to serve static files instead of Rails because Nginx is way faster for that purpose. If you set the `root` path in the nginx `server` block to point to the `public/` directory of wherever you cloned the repository, it should be able to serve the assets and uploads and the static files from there.

**Comment by alexgleason** [comment]
Yep, makes sense! I've done this in Django too. I was a little thrown off by the fact the readme ends before addressing this, since I've seen some projects contain nginx as a service inside of the docker-compose. Thought there might be some magic I was missing somewhere. I submitted a PR #320 to hopefully fix this for future users. Thanks!
