### ISSUE TITLE
Labels for the sensitive and unlisted toggles

### ISSUE THREAD

**Issue by triplefox** [Gargron/mastodon#330]
As suggested by XKeeper. 
![media](https://cloud.githubusercontent.com/assets/1550842/20806305/42a685d8-b7af-11e6-8288-49c5301e387f.png)

**Comment by Gargron** [comment]
I think this is not necessary anymore now that "Unlisted mode" has been renamed to "Don't show on public timeline". Sensitive content is still a bit blurry but I really don't want to add more visual weight to the toggles by adding extra text.
