### ISSUE TITLE
Toggle between mentions and notifications

### ISSUE THREAD

**Issue by triplefox** [Gargron/mastodon#332]
The mentions-only view is being asked for again, and while it's possible to reach it with https://mastodon.social/web/timelines/mentions it would be nice to surface it in the UI. Maybe some kind of tab or link at the top of the column?

**Comment by Ragzouken** [comment]
yes, i would like to be able to replace notifications with mentions so i can still see the public timeline. i'm not very interested in my own stars/retoots

**Comment by hoodiek** [comment]
i have updated #244 to encompass this and other issues. I recommend closing this and focusing notifications enhancements in #244

**Comment by swaldie** [comment]
Thanks for your hard work @hoodiek.  I will, as fae mentioned, be closing this and relating it to #244.
