### ISSUE TITLE
Disallow digit-only hashtags

### ISSUE THREAD

**Issue by marrus-sh** [Gargron/mastodon#333]
On Twitter and other sites, hashtags which consist only of characters in the `[0-9]` ASCII range are not allowed, to allow the additional use of # as a number sign (see https://mastodon.social/users/marrus_sh/updates/348872 for an example). It is not *strictly* necessary that Mastodon follow this behaviour, as users could always use a fullwidth hash `＃` or the less ambiguous numero sign `№` as their number sign instead, but I figured raising the issue/discussion would be worthwhile.

**Comment by TazeTSchnitzel** [comment]
What are the OStatus/GNU Social/etc. rules for this, if any?

**Comment by Gargron** [comment]
There are no rules at all. For example, GS allows periods in hashtags, which imo is a terrible choice when people end their sentences with #hashtags. I mean, this shouldn't be too hard to fix with a slightly pickier regex... Like, hashtag can't consist of only digits. Not actually sure how to write that out right now, here is the regex in question:

https://github.com/Gargron/mastodon/blob/master/app/models/tag.rb#L6

**Comment by marrus-sh** [comment]
Should be

```rb
/(?:^|[^\/\w])#([[:word:]_]*[[:word_except_numbers:]_][[:word:]_]*)/i
```

where `:word_except_numbers:` is all the word characters except for digits. Ensures that one non-digit character exists but allows any number of characters before or after

**Comment by marrus-sh** [comment]
**Update:** The POSIX class you want is `[:alpha:]`

```rb
/(?:^|[^\/\w])#([[:word:]_]*[[:alpha:]_][[:word:]_]*)/i
```

will do it, with the minor exception that it also disallows hashtags consisting entirely of connector punctuation (which shouldn't be a problem, as connector punctuation wouldn't make sense in isolation anyway). You could also remove the underscore here if you want to prevent, ie `@_@` from showing up with the hashtag `@_` (as it now does).
