### ISSUE TITLE
SSL errors for url mastadon.social

### ISSUE THREAD

**Issue by kumavis** [Gargron/mastodon#339]
![image](https://cloud.githubusercontent.com/assets/1474978/20892146/c5bee6c6-bac1-11e6-9031-319457ba910b.png)

**Comment by Gargron** [comment]
Please let me know if this persists longer than a few hours. I've enabled Cloudflare on the asset subdomains to save on bandwidth costs. This could be a temporary issue.

**Comment by swaldie** [comment]
At this time, this issue is being considered resolved, as the root cause is believed to be the enabling of CloudFlare.  Please let someone know if SSL errors persist.
