### ISSUE TITLE
[ Design request ] - Animal Liberation Background

### ISSUE THREAD

**Issue by moshpirit** [Gargron/mastodon#347]
Hello, first of all I want to thank you all your hard work and dedication to this amazing project. I also like Mastodon, BTW ;) and also I'm an Animal Rights advocate (and of course a vegan) so I opened my account here in [Animal Liberation](https://animalliberation.social/) but I think that [the background](https://animalliberation.social/assets/background-photo-6ac11c58dee9afc64493b335470c838ede6259203cb515d373d6c269433fead2.jpg) can be improved, so I checked [lots of pictures with public license](https://www.flickr.com/search/?text=animal&license=7%2C9%2C10) and selected a few:

- [ally](https://www.flickr.com/photos/johnsy/5144277598/)
- [paradise shelduck young](https://www.flickr.com/photos/volvob12b/8692599430/)
- Tiger: [1](https://www.flickr.com/photos/mathiasappel/13582313234/), [2](https://www.flickr.com/photos/mathiasappel/15694751682/)
- [Proud as a Peacock](https://www.flickr.com/photos/volvob12b/16853387384/)
- [Peacock 2](https://www.flickr.com/photos/santamonicamtns/11074242195/)
- [Fidelity](https://www.flickr.com/photos/57736600@N02/15434847114/)
- [Ducklings](https://www.flickr.com/photos/volvob12b/8691410057/)
- [HEy, IT's yOu! (Explored)](https://www.flickr.com/photos/129822560@N05/16837941274/)
- [Chiqui](https://www.flickr.com/photos/milkyfactory/10609381933/)
- [Palmyre-52](https://www.flickr.com/photos/lymatly/17371586395/)
- [Palmyre-142](https://www.flickr.com/photos/lymatly/16751336163/)
- [Big Dog Skagway Alaska](https://www.flickr.com/photos/volvob12b/9283238396/)

*Maybe I update this issue with more pics ;)*

Note the irony that some of these photos were taken on a zoo.

Again, thank you so much!

**Comment by swaldie** [comment]
Thanks for bringing this here! However, this is specifically for issues that deal with Mastodon (the greater) project and to a lesser extent, the public instance mastodon.social.  For changes that pertain to other instances, please reach out to those instance admins.

**Comment by moshpirit** [comment]
Sorry and thank you! Didn't know was made by a different guy! (found him but maybe it would be a good idea to attach a link to the admin of the instances in the wiki)

**Comment by alexgleason** [comment]
Hi @moshpirit 

Thanks for the suggestion! I've uploaded my fork of Mastodon here. https://notabug.org/AnimalLiberationNetwork/AnimalLiberation.social

Note that it's far from complete. I kind of just hacked the Mastodon core, but the code needs to be cleaned up quite a bit. Anyway, it would be great if you reopen this issue on the new repository! I'm open to any other feedback you have, and if you'd like to help with this project I'd be happy to review a PR.

Thanks!
