### ISSUE TITLE
Unicode emoji variation selectors are handled backwardly

### ISSUE THREAD

**Issue by marrus-sh** [Gargron/mastodon#349]
According to [the Unicode Techincal Report on emoji](http://www.unicode.org/reports/tr51/#Emoji_Variation_Sequences), `U+FE0E VARIATION SELECTOR-15` should be used to indicate a text representation, while `U+FE0F VARIATION SELECTOR-16` should be used to indicate an emoji representation. The behaviour of EmojiOne on the main timeline is opposite; see the image below:

<img width="336" alt="image" src="https://cloud.githubusercontent.com/assets/3212430/21040354/3e2124ce-bd99-11e6-87fc-3b0efbd453fb.png">

(You will note in the case of the Trademark sign the Apple Color Emoji was selected instead)

These characters in particular (the copyright, trademark, and registered trademark signs, along with a few others) should (by Unicode) not be interpreted as emoji *unless* `U+FE0F` is present, as they are more frequently employed in their non-emoji form.

---

**EDIT:** The static version of the above toot is at https://mastodon.social/users/marrus_sh/updates/410247 if you want to verify the characters/sequences yourself

**Comment by marrus-sh** [comment]
Researching it a little further, I think this is just an issue with EmojiOne, not on your end, actually? See:

- Ranks/emojione#301
- Ranks/emojione#320
- Ranks/emojione#392

I would be hesitant to do any kind of normalization that got rid of variation selectors, as those might also interfere with the display of some Han characters. I *believe* that just removing `U+FE0F` from the input string anywhere it's present would be a safe fix, if you wanted to solve this in the meantime? Otherwise it's just a matter of waiting for EmojiOne to fix things on their end.

**Comment by swaldie** [comment]
I think we're waiting for EmojiOne on this issue.

**Comment by ticky** [comment]
Hey, why did this get closed? It’s still a bug that hasn’t been fixed!

Copying from #1234,

> It looks like emojione 3.0 fixes this (Ranks/emojione#415), but we can’t use it until emojione-picker updates its dependency.

This issue should be reopened until a patch adding emojione 3.0 (and emojione-picker’s update for 3.0) lands.
