### ISSUE TITLE
inability to expand toots when the toot consists of mostly clickable interactables

### ISSUE THREAD

**Issue by hoodiek** [Gargron/mastodon#352]
https://mastodon.social/users/Gargron/updates/434267

this toot appeared on my timeline and there is specifically no place to view the full context of the post, so i would suggest adding an option to open it like that here: 
![image](https://cloud.githubusercontent.com/assets/23704040/21083183/e6b2fd6c-bfb8-11e6-9e54-5a1902490cd8.png)

as "context" or "details"

here's a screenshot of that toot in my timeline to show how absurdly little space there is to click to see the full context: 
![image](https://cloud.githubusercontent.com/assets/23704040/21083197/26248858-bfb9-11e6-9cf5-758186c7d659.png)
the only place to click is all the way to the right, just past the mastodon.social/media link, approx 1 or 2 pixels of space to hit

**Comment by Gargron** [comment]
Added
