### ISSUE TITLE
ctrl+v images aka paste images into the toot box to upload

### ISSUE THREAD

**Issue by hoodiek** [Gargron/mastodon#353]
i know we just got another great addition to uploading images easier, i would personally really appreciate copy-pasting in, since i use ShareX, a tool that automatically adds my screenshots into my paste queue so i can do screenshots much easier if this was implemented.

I will however note there are much more important things to work on, so i don't mind if this gets put on the backburner.
i personally thing muting tools being expanded and private accounts are a priority over it, but figured i'd make an issue for this anyway, so i dont forget

**Comment by marrus-sh** [comment]
See #221!

**Comment by hoodiek** [comment]
oops, gotcha, gonna close. thanks for the pointer
