### ISSUE TITLE
Emoticon using @ symbol causes user to get mentioned

### ISSUE THREAD

**Issue by dhprototype** [Gargron/mastodon#354]
I have an account with underscore(_) as an id on mastodon.social. I get about a notification a day for being mentioned in a post. When I look at the posts, it mostly contains this emoticon - @_@

**Comment by Gargron** [comment]
This isn't really a bug, albeit an inconvenience for you... So that @\_@ string is a mention with a username and domain part, where the domain part is empty, therefore local. So it's the same as @\_.
