### ISSUE TITLE
kickass.zone looks down, remove it from the list of Mastodon instances page

### ISSUE THREAD

**Issue by olistik** [Gargron/mastodon#358]
[https://kickass.zone looks down](http://downforeveryoneorjustme.com/kickass.zone)
Should we remove it from the wiki page [List of Mastodon instances](https://github.com/Gargron/mastodon/wiki/List-of-Mastodon-instances) or at least convert that list into a table with "status" and "last check at" columns?

**Comment by swaldie** [comment]
Confirmed kickass.zone is no longer reachable, removed.
