### ISSUE TITLE
privacy superpost: private accounts, and backwards compatibility in regards to federation

### ISSUE THREAD

**Issue by hoodiek** [Gargron/mastodon#359]
there are a few things to unpack, here.

first: i have not seen a sufficient explanation of what is necessary for a private account.

here is a sum up of what i think is sufficient, and could be implemented on a singular basis, ie, each feature could be toggled on and off individually.

- inability to be followed without permission from owner of account
- inability of posts to be found via search engines such as google or duckduckgo, etc.
- inability of user profiles to be found via search engines such as google or duckduckgo, etc.
- inability of posts to be seen in client by user if not following
- inability to be seen if the user is not following
- inability for toots to be boosted

there is more i think, to this, however, that has not been mentioned, and i think would be good additions. the unlisted option is a wonderful example of this, the ability to limit posts to only your followers, or, to a specific list of authorized users would allow for people to much safer share information on different levels of trust, which allows someone to have a public account, and use it for all things, such as nsfw things, sad things they do not wish to share with the public, personal details, etc.

blocking should effectively hide a user in the same way as all of these options to be turned on, thus hiding all posts, notifications, etc. for all further posts

if this sounds very harsh in terms of not allowing backwards compatibility, i would like to offer this plea:

open source is BUILT on the concept of improving software, of allowing change through new thinkers doing new things. as such, it is worth acknowledging that the current mechanism of federation is broken when it comes to the urgent need of private accounts.

this means the obvious next step is to iterate. fix it. break compatibility if necessary.

so when is it necessary to break compatibility? when a user chooses any options that can not federate, said posts DO NOT FEDERATE. it's really that simple!

as such, i would suggest that when someone selects options that break federation, their posts will not federate. this requires a per-post basis, or easier access than via the settings menu. this still allows for backward compatibility, it is worth noting: anyone who does not feel the need for these options can simply ignore them, and will federate. but mastodon instances can interact with each other appropriately to meet these needs, and i believe it is necessary to do so.

further notes: my understanding from #180 is this can be accomplished through users who choose such options to distribute primarily or maybe even purely through the salmon protocol. i would suggest this for posts of such type, and this would seemingly federate between mastodon instances just fine, but it wouldn't to the fediverse that does not innovate along with us, and that is fine.

sometimes the best avenue to change is not to bicker with and beg change from people who will not give it, but instead, to leave them behind.

"what if federation doesn't follow suit?"

leave them behind.

i would suggest any information that we should carry it over from #180 be moved here, and #180 be closed, as this issue is better organized and better addresses the needs that must be met to create privacy and private accounts

i would also like to formally say that the details are not something i understand, in the most technical terms.

EDIT: reworded sum-up
Account settings that are necessary:
- follow requests/follow vetting

post-specific settings, which can be changed on a per-post basis. I also suggest account settings for "post defaults" which would also contain an unlisted option to make it default to unlisted posts

- inability to see posts without being logged in and following user
- inability of posts to be found via search engine
- hiding posts to non-followers
- inability of posts to be boosted

also, since privacy stuff can have a default-setting for all posts, it's worth it to make it reset to the default whenever the toot button is pressed.

EDIT2: removed an already existing feature

**Comment by coolstar** [comment]
👍 for this. There were several times where I found myself going back to the bird site as there were some things I wished to communicate to others but privately. It would be great if Mastodon could get private accounts.

**Comment by triplefox** [comment]
Just today I saw relationships get hurt because a personal thing got boosted when it wasn't desired. Let's see some action on this.

**Comment by hoodiek** [comment]
another thought that leaked up into the forefront of my mind. just above the post a temporary or maybe even permanent. "will not federate to GNUsocial", "will federate" and "will not federate to any other instances" as a frank descriptor of features that do not have full implementation and what the post you are currently tooting will do

**Comment by hoodiek** [comment]
this will theoretically allow more temporary solutions to work in mastodon itself to allow the tools people need, while more advanced solutions are worked on, and federation itself may be iterated on

**Comment by modgethanc** [comment]
I think marking features for federating behavior could be a very good middle ground here.

**Comment by haniawni** [comment]
I'm a big fan of this approach, though I wonder about UI design and how to ensure it's welcoming to New users, cause these options will make very explicit (and require understanding of) the federated structure of GNUSocial.

I'd love to see a prominently displayed "what the fuck do all these switches do" thing to explain via diagram/screenshots what exactly each switch does. Can help with screenshots/help text but will have spotty internet next few days

**Comment by hoodiek** [comment]
a difficult request i have, but one that i think is the best way to improve twitter's privacy options, and overall increase safety for harassment-targeted users is to enforce auto-privacy on post-specific privacy options to any replies to said toots. what this means is, if i reply to a toot that cannot be boosted, is hidden except to the user's followers, etc, the same settings would automatically require that the same privacy options are added to each reply to said post. hope this makes sense, and honestly the first step is meeting twitter's functionality as a baseline, and allowing said options to be applied Per Post. purely meeting this need is enough to satisfy most users, although i think the extension i mention here is a logical evolution to follow

**Comment by marrus-sh** [comment]
^ This is something that I was thinking as well; replies to a post should never be more public than the original post. Ideally, this would mean enforcing privacy features all the way down the chain; alternatively, it might mean that replies which are less private than their parent posts be automatically unlinked from them and just treated as an @-mention.

**Comment by hoodiek** [comment]
i think this post can be closed as finished, now. we got all the posting options we really need for private accounts and the like, the only issue remains stuff that is bonus stuff, new features i'd call them. we can make seperate issues for these, and i will

**Comment by Gargron** [comment]
Alright!
