### ISSUE TITLE
OEmbed of media post URLs only give the media URL

### ISSUE THREAD

**Issue by Hypolite** [Gargron/mastodon#361]
Example: https://friendica.mrpetovan.com/display/52acf9cde51b84b00c8af4321821efdf0cb1bc27

Friendica's OEmbed handler is trying to get the OEmbed display from the original post URL (https://mastodon.social/users/BadWrongFun/updates/482304) and the only thing it gets it the Mastodon media URL (https://mastodon.social/media/47716).

It may be an issue with Friendica's OEmbed  handler but it could also be a problem with Mastodon OEmbed display.

**Comment by Gargron** [comment]
At the moment the OEmbed `html` output is simply the text (well, html) contents of the status. I'll need to see an example of how others do it, for example, I heard that it's good practice for the `html` to return an iframe pointing to a page on the original site with a rich presentation of the content. Would that be fitting?

**Comment by Hypolite** [comment]
Yes, I believe it's the intended purpose of OEmbed. In the case of an media post, it displays the image, in the case of a video, it shows a player, etc...

**Comment by Hypolite** [comment]
Thanks! Can I expect to see the changes immediately from mastodon.social?

**Comment by Gargron** [comment]
You should see them now, yes.

**Comment by Gargron** [comment]
Please give me a link since I'd like to see how they look on the other end

**Comment by Hypolite** [comment]
Here it is: https://friendica.mrpetovan.com/display/00000000bdfbbc5fb76b4055e5de8d967fa4de1d

My comment: the image shows up which is great, but so the rest of the whole post when we only expect the image to show. I think it comes from the fact that the media post include a link to itself (http://mastodon.social/media/49063 in the case at hand), and Friendica displays it as such.

**Comment by Hypolite** [comment]
Another example with multiple images: https://friendica.mrpetovan.com/display/52acf9cd9d91943b07528a316ba8737d178d4f88

Friendica correctly identifies the two image attachments (the two grey image icon at the bottom, and at the same time tries to show the OEmbed version of the first link present in the status (in this case:  http://mastodon.social/media/48993)

Are those `media/*` links serving a particular purpose in the body of statuses? I expected them to be the direct URL to the attached images but they just are redirecting to the full status update.

**Comment by Gargron** [comment]
They serve as a backup for when a client does not display images or attachments, the links symbolize that something is there.

What's weird is that it seems like Friendica has both the normal status in the Friendica UI, and inside it, it embeds the status via OEmbed again. Is that what you mean, is it because of the media links? But there's a redirect in there, surely OEmbed discovery wouldn't work with a redirect inbetween..?

**Comment by Hypolite** [comment]
Friendica's behavior isn't weird, it's actually doing exactly what we should expect from it given the self-referential nature of the links included in the media posts. If anything, those are weird, especially for the multiple image posts where all the `media/*` links actually redirect to the same status update.

What about putting the URLs of the actual images instead, so that clients not getting attachments can do something with them?

**Comment by Gargron** [comment]
Okay, media URLs now redirect to the file, so this should be resolved.

**Comment by Hypolite** [comment]
That's great, I'll wait for your next media post to show you what's the end result on Friendica.

**Comment by Gargron** [comment]
Just posted something.

**Comment by Hypolite** [comment]
Here it is:
https://friendica.mrpetovan.com/display/52acf9cd35383843761cbc8783a514fbf9acb482
