### ISSUE TITLE
Tagged user dropdown UI, stuck on screen

### ISSUE THREAD

**Issue by grimedango** [Gargron/mastodon#370]
![2016-12-23 10_58_28-mastodon - opera](https://cloud.githubusercontent.com/assets/18517143/21457656/115fa444-c8ff-11e6-94d0-ca592be33cf0.png)

After a toot, getting the tagged person's username stuck in this drop down. Can't seem to select it, either.

**Comment by Gargron** [comment]
See #357 for progress

**Comment by Gargron** [comment]
Even though I love your userstyle every time I see it
