### ISSUE TITLE
Serving 404s when attempting to view private posts while not logged in

### ISSUE THREAD

**Issue by nikitahaley** [Gargron/mastodon#374]
Repro steps:
1. log out
2. go directly to url of private post
3. HTTP 404

Shouldn't be serving 404s for posts that exist and the user is unable to see due to login status or something and indicates to the user that the problem is on the server's end and not on theirs (they aren't logged in like scrubs)

**Comment by Gargron** [comment]
No this is intended behaviour. There is no reason to leak the fact of existence of a private post.

**Comment by zcdunn** [comment]
> 403 Forbidden
Client does not have access rights to the content so server is rejecting to give proper response.
404 Not Found
Server can not find requested resource. This response code probably is most famous one due to its frequency to occur in web.

Shouldn't it be serving 403 instead?

**Comment by hoodiek** [comment]
no, because a 403 admits that there is something to show.
404 hides overall, does not leak the existence of a post.

**Comment by nikitahaley** [comment]
If using the wrong error code entirely is by design, there should at least be a mastodon-served "there's nothing here!" page instead of a generic browser 404. That gives the user the opportunity to see somewhere on-screen that they aren't logged in and resolve the issue themselves instead of just jumping to the conclusion that the problem is something wrong with the URL or mastodon itself.
