### ISSUE TITLE
Bio doesn't show on static profile pages

### ISSUE THREAD

**Issue by marrus-sh** [Gargron/mastodon#382]
It makes sense to hide bios on profiles in the timeline view to conserve space, but they should still be visible when you click to open the profile as a static page; e.g., https://mastodon.social/users/marrus_sh (currently it is hidden here as well). Otherwise, there is no way to view profile bios on mobile devices!!

**Comment by TrevInc** [comment]
I can successfully reproduce this bug

This happens when the window height is beneath the media query (max-height:800px), but it should show on user pages, especially on desktop or tablet-horizontal when the width still allocates space for the bio.

**Comment by TrevInc** [comment]
Worth noting that the 800px query means that users on 1366x768 laptops, of which there are many, will never be able to see bios.

**Comment by Gargron** [comment]
Fixed by #389
