### ISSUE TITLE
Allow users to specify image alt text

### ISSUE THREAD

**Issue by marrus-sh** [Gargron/mastodon#383]
(Actually, since images are specified using `<a style="background-image: url(…);">` and not `<img>` this would use the [`aria-label` attribute](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/ARIA6))

This is an accessibility feature provided by Twitter (although it must be first activated in user preferences), allowing users to provide alternate text for images that they upload. It also might provide an alternate means for including content warnings for images as in #239 – instead of just “Sensitive content: click to view” the alt text for the image could be displayed instead.

**Comment by kewball** [comment]
#117 seems to cover this

**Comment by marrus-sh** [comment]
true; will add my comments there
