### ISSUE TITLE
Proposal: timeline should show fav/boost/reply counts

### ISSUE THREAD

**Issue by charlag** [Gargron/mastodon#420]
Thank you for you awesome work.

It may be a nice thing to quickly see fav/boost/reply count, frees users from checking toot manually every time.
I think this is not top priority right now but still worth implementing in the future.

**Comment by Gargron** [comment]
This will not happen. Some people have expressed relief that you *can't* see those numbers at a glance, which means they matter less, which means toots are more equal on the timelines. Sorry.

**Comment by Gargron** [comment]
Unfortunate that this issue got the number 420 and had to be closed so quickly 😢

**Comment by charlag** [comment]
@Gargron you mean it helps federalization? If not, it could be just a simple option.

Sorry for spoiling the number.
