### ISSUE TITLE
Can't get to profile page from the timeline

### ISSUE THREAD

**Issue by jhauberg** [Gargron/mastodon#73]
Looking at the post below, it mentions using the profile page to start following more people:

![screen shot 2016-10-06 at 11 20 09](https://cloud.githubusercontent.com/assets/1360637/19147108/dfdb632a-8bb6-11e6-8c6a-8c601e1611e9.png)

However, you can't get to the profile page with the list of followers/following from the main timeline. You only get this:

![screen shot 2016-10-06 at 11 17 50](https://cloud.githubusercontent.com/assets/1360637/19147049/8fb58b8c-8bb6-11e6-9b10-daf56ca9cbd5.png)

There should be a way of getting to the profile page. Additionally, once you get there, you can't easily follow that person's followers/followings (see #72).

**Comment by Gargron** [comment]
Right! It's not super obvious, but middle-mouse-clicking or right-click->open in new tab on usernames in the UI will open the public (potentially on a remote server) profile of the person, while left-click opens it in the UI. I should add a link to the former from the latter though... and follower/following counts too. The reason for the absence of the latter is that I'm not currently sure how to best present them design-wise.

**Comment by jhauberg** [comment]
Yea, I figured it out. I think it's totally fine having it work like this, but I think everyone would benefit if it was a part of the UI and easily navigable. Simple suggestion:

![screen shot 2016-10-06 at 11 32 05](https://cloud.githubusercontent.com/assets/1360637/19147478/9342ed38-8bb8-11e6-85d8-0f995897551d.png)

Make this a link that opens a new tab :)

Or use the full name so it works exactly like in the timeline.
