### ISSUE TITLE
Scroll to top when clicking feed header

### ISSUE THREAD

**Issue by jhauberg** [Gargron/mastodon#76]
This is a suggestion to have the feed scroll to the top when clicking the feed header.

![scroll-to-top-suggestion](https://cloud.githubusercontent.com/assets/1360637/19152005/23404838-8bd0-11e6-8efb-46f2ce17b6fa.png)

I already found myself several times trying to click here, expecting it to scroll up. I think it would be a convenient and obvious way to get back to the top.

**Comment by jhauberg** [comment]
In addition, in case new posts have been added since scrolling down, it should probably only scroll to the post that was at the top when you started scrolling down (and indicate that there are more posts above- see #38).

**Comment by Gargron** [comment]
I'm confused because it does already scroll to top when you click that! On Firefox at least, what browser are you on?

**Comment by jhauberg** [comment]
Oh, I'm on Safari, El Capitan. I did briefly try to debug whether it was already meant to scroll by inspecting the source, but encountered a garbled/minified wall of text and just went to file an issue instead 😬
