### ISSUE TITLE
Hide "more" menu if there's no options

### ISSUE THREAD

**Issue by jhauberg** [Gargron/mastodon#78]
If there's no options, the "..." button should not be visible.

![screen shot 2016-10-06 at 14 28 00](https://cloud.githubusercontent.com/assets/1360637/19152199/3b3e9a10-8bd1-11e6-9568-d952c70e905a.png)

**Comment by Gargron** [comment]
I'm gonna add options like "Mention user", "Report" in the future

**Comment by Gargron** [comment]
Now there's always a "mention" option
