### ISSUE TITLE
Scrollbar design issue

### ISSUE THREAD

**Issue by mechadrops** [Gargron/mastodon#80]
So currently Mastodon uses the browser's default scrollbar design, which unfortunately clashes with the website's overall darker theme. It wouldn't be too hard to change its size and color with some CSS, and in return you'll have two advantages:
1) a design element that doesn't clash with the rest of the website
2) thinner scrollbar = more space for actual content in the column
The difference is especially noticeable on a comparison screenshot:
![scrollbar](https://cloud.githubusercontent.com/assets/17452575/19159350/c4fa867e-8bf4-11e6-9329-1b5ae591f6f7.png)

And just in case, here's the CSS I used for the scrollbar in that picture:
```
::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}
::-webkit-scrollbar-thumb {
  background: #42495b;
  border: 0px none #ffffff;
  border-radius: 50px;
}
::-webkit-scrollbar-thumb:hover {
  background: #525a70;
}
::-webkit-scrollbar-thumb:active {
  background: #42495b;
}
::-webkit-scrollbar-track {
  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
  border: 0px none #ffffff;
  border-radius: 50px;
}
::-webkit-scrollbar-track:hover {
  background: #282c37;
}
::-webkit-scrollbar-track:active {
  background: #282c37;
}
::-webkit-scrollbar-corner {
  background: transparent;
}
```

**Comment by Gargron** [comment]
I'll add this in though I do wish it was compatible with Firefox as well :( But I know you can't customize scrollbars in it.

**Comment by mechadrops** [comment]
Oh man, I completely forgot about the browser compatibility. Yeah, it seems like it would only work for WebKit browsers for now.
