### ISSUE TITLE
Support adding hashtags to posts (and maybe to oneself)

### ISSUE THREAD

**Issue by localhost** [Gargron/mastodon#81]
This would be great to discover interesting posts/people.

**Comment by Gargron** [comment]
So... The hashtag feed itself could perhaps be accomplished with Postgres full-text search for #keyword. The real-time updates would be slightly more challenging... `FanOutOnWriteService` is growing up fast. Basically you'd want to take the status body, scan it for #keywords and broadcast to ActionCable for every keyword found.

**Comment by jimmytidey** [comment]
I wonder if there would be a benefit of having a table of of hashtatgs associated with the id of the message they came from. That would mean you wouldn't need to do a fulltext search. 

It would also make features like autocompletion and trending tags possible.

It seems almost intrinsic to the notion of a hashtag that the user is marking out a phrase for special treatment above just full text search. 

The same table might be useful for other entities, such as URLs or embedded media.

**Comment by cphuntington97** [comment]
Even just basic search functionality would be great.

But a huge source of value in a microblogging platform (for me) is the live updating of content during a live event.

**Comment by Gargron** [comment]
:white_check_mark:
