### ISSUE TITLE
Don't show reblogs if you're following the original poster

### ISSUE THREAD

**Issue by RexMorgan** [Gargron/mastodon#82]
It would alleviate duplicates in the timeline like this:

![image](https://cloud.githubusercontent.com/assets/178752/19166711/3fdacd58-8bce-11e6-9350-12e43e316261.png)

**Comment by Gargron** [comment]
It already de-duplicates in the back-end (e.g. if you refresh you'd see) but updates coming in in real-time don't, I need to make the JS filter for that. Will do.
