### ISSUE TITLE
Strip EXIF from uploaded images

### ISSUE THREAD

**Issue by vayan** [Gargron/mastodon#85]
Hi,

For privacy reasons could we strip EXIF metadata from images ? 

At least the GPS data ? And maybe keep the "Taken on" date.

example here : https://mastodon.social/users/vayan/updates/14461

**Comment by Solido** [comment]
I would be glad to have it as an option only. Tomorrow I'll be glad to have a plugin that can Map all the pics I took. 

Maybe having this as an option at the moment we send pictures ?

**Comment by Angristan** [comment]
Or an option in user settings, disabled by default.
