### ISSUE TITLE
Zoom issues

### ISSUE THREAD

**Issue by ianchanning** [Gargron/mastodon#86]
I'm on Windows 10, FF 49. In default 100% zoom, the site is too wide. In 90% zoom the site is too small (leaves blank space at the right edge).

Resolution is 1600 x 900.
### 100%:

![2016-10-07 11_27_28-mastodon](https://cloud.githubusercontent.com/assets/233318/19185600/9b5f01da-8c82-11e6-9649-e56007992414.png)
### 90%:

![2016-10-07 11_27_46-mastodon](https://cloud.githubusercontent.com/assets/233318/19185608/a2ba284c-8c82-11e6-989a-402378f3799d.png)

**Comment by jhauberg** [comment]
Similarly, at 90% (Safari), the profile following/followers description boxes go bad:

![screen shot 2016-10-07 at 11 47 05](https://cloud.githubusercontent.com/assets/1360637/19185904/f13cf1d8-8c83-11e6-9b1d-68d20ec518e6.png)
