### ISSUE TITLE
Account creation: Password considered invalid. (or email?)

### ISSUE THREAD

**Issue by ng-0** [Gargron/mastodon#94]
I've tried a test signup in the web browser with a rather long password involving letters and characters from the ranges of A-Za-z0-9#*;.-^

I can imagine (due to not reading the code yet) that it's one or more of the following issues:

- "#" is considered invalid
- length of the password is too long

**Comment by ng-0** [comment]
Food for thought: it could also be my .is domain ... which is totally valid and a long accepted top level domain. I've tried with passwords resembling words and sentences, and it still failed.

This all has been tested on what I believe is the showcase instance, mastodon.social.

**Comment by Gargron** [comment]
What actual error message have you got?

**Comment by ng-0** [comment]
Sorry, I was focused on describing the issue but forgot to include the message.

"Invalid Email or password."

**Comment by Gargron** [comment]
That looks like a message on the login form when you're trying to sign in with invalid credentials. Are you sure you are on "sign up" page?

**Comment by ng-0** [comment]
Okay.. got me there. Let me close this bug and open another one for what this really was about.
