### ISSUE TITLE
Fix 'follow' function for gnusocial users

### ISSUE THREAD

**Issue by ng-0** [Gargron/mastodon#95]
Currently it seems that following profiles located on mastodon instance(s) is not possible if you use gnusocial (for example quitter.se). Gnusocial allows to follow remote instances which are compatible to certain code.

**Comment by Gargron** [comment]
When did you try this? It was working a few days ago.

**Comment by ng-0** [comment]
As per issue #94 you can see that I have no account at mastodon.social (and I've only just started a build on Guix, shot in the dark), so this is quitter.se -> mastodon.social ... I'm not sure how the follow is supposed to look like. Someone from mastodon.social followed my account at quitter.se, this is how I discovered mastodon. I wanted to follow back but saw no public button to achieve following from gnusocial. Now I can't tell if it's a bug or a feature because I only know one profile and have just discovered the software.

**Comment by ng-0** [comment]
Correction: It worked from the most obvious, yet unexpected place: the subscribers page on the gnusocial instance my own profile is at! Nothing broken, just me thinking in patterns too much focused on debugging things :)
