### ISSUE TITLE
"Get me started" button should lead to signup page

### ISSUE THREAD

**Issue by ng-0** [Gargron/mastodon#96]
From the perspective of a new user, the "Get me started" leads to thinking that the page you land on is the sign up page. The link to the sign up page is too small to recognize that you are in error if you do not read the file name and think that you are just about to sign up.
This leads to effects like #94 

I would suggest to make sign up more visible: bigger, the font in general is small or just make it stand out somehow.. but what could also happen is:
Default to register, make the login page a link on the register page.

**Comment by Gargron** [comment]
Added links to both from about page
